### ISSUE TITLE
500是什么问题？

### ISSUE THREAD

**Issue by izonewonyoung** [sugarforever/chat-ollama#10]
E:\chat-ollama\chat-ollama-main>npm run dev

> dev
> nuxt dev

Nuxt 3.10.3 with Nitro 2.9.1                                                                                  20:26:23
                                                                                                              20:26:23
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

i Using default Tailwind CSS file                                                            nuxt:tailwindcss 20:26:24
  ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                   20:26:25

i Tailwind Viewer: http://localhost:3000/_tailwind/                                          nuxt:tailwindcss 20:26:25
i Vite client warmed up in 3218ms                                                                             20:26:29
i Vite server warmed up in 3004ms                                                                             20:26:29
√ Nuxt Nitro server built in 425 ms                                                                     nitro 20:26:29
Ollama:  {
  host: 'http://localhost:11434',
  username: undefined,
  password: undefined
}
Ollama:  {
  host: 'http://localhost:11434',
  username: undefined,
  password: undefined
}
Error fetching knowledge bases:  PrismaClientInitializationError:
Invalid `prisma.knowledgeBase.findMany()` invocation in
E:\chat-ollama\chat-ollama-main\server\api\knowledgebases\index.get.ts:6:1

  3 const listKnowledgeBases = async (): Promise<KnowledgeBase[] | null> => {
  4   const prisma = new PrismaClient();
  5   try {
→ 6     return await prisma.knowledgeBase.findMany(
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   |
 2 |   provider          = "sqlite"
 3 |   url               = env("DATABASE_URL")
   |

Validation Error Count: 1
    at _n.handleRequestError (E:\chat-ollama\chat-ollama-main\node_modules\@prisma\client\runtime\library.js:123:7154)
    at _n.handleAndLogRequestError (E:\chat-ollama\chat-ollama-main\node_modules\@prisma\client\runtime\library.js:123:6188)
    at _n.request (E:\chat-ollama\chat-ollama-main\node_modules\@prisma\client\runtime\library.js:123:5896)
    at async l (E:\chat-ollama\chat-ollama-main\node_modules\@prisma\client\runtime\library.js:128:10871)
    at listKnowledgeBases (E:\chat-ollama\chat-ollama-main\server\api\knowledgebases\index.get.ts:6:1)
    at Object.handler (E:\chat-ollama\chat-ollama-main\server\api\knowledgebases\index.get.ts:18:1)
    at async Object.handler (file:///E:/chat-ollama/chat-ollama-main/node_modules/h3/dist/index.mjs:1962:19)
    at async toNodeHandle (file:///E:/chat-ollama/chat-ollama-main/node_modules/h3/dist/index.mjs:2249:7)
    at async ufetch (file:///E:/chat-ollama/chat-ollama-main/node_modules/unenv/runtime/fetch/index.mjs:9:17)
    at async $fetchRaw2 (file:///E:/chat-ollama/chat-ollama-main/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:219:26) {
  clientVersion: '5.10.2',
  errorCode: undefined
}
Ollama:  {
  host: 'http://localhost:11434',
  username: undefined,
  password: undefined
}
[nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'map')
  at E:\chat-ollama\chat-ollama-main\pages\knowledgebases\index.vue:122:36
  at ReactiveEffect.fn (E:\chat-ollama\chat-ollama-main\node_modules\@vue\reactivity\dist\reactivity.cjs.js:998:13)
  at ReactiveEffect.run (E:\chat-ollama\chat-ollama-main\node_modules\@vue\reactivity\dist\reactivity.cjs.js:181:19)
  at get value [as value] (E:\chat-ollama\chat-ollama-main\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1010:109)
  at unref (E:\chat-ollama\chat-ollama-main\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1132:29)
  at Object.get (E:\chat-ollama\chat-ollama-main\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1138:35)
  at _sfc_ssrRender (E:\chat-ollama\chat-ollama-main\pages\knowledgebases\index.vue:357:18)
  at renderComponentSubTree (E:\chat-ollama\chat-ollama-main\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:695:9)
  at E:\chat-ollama\chat-ollama-main\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:639:25
  at async unrollBuffer$1 (E:\chat-ollama\chat-ollama-main\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:882:16)

**Comment by sugarforever** [comment]
看起来应该是SQLite数据库没有创建。

运行以下命令再尝试下。

```
npm run prisma-migrate
```

我会尽快更新文档。

**Comment by izonewonyoung** [comment]
E:\chat-ollama\chat-ollama-main>npm run prisma-migrate

> prisma-migrate
> prisma migrate dev

Prisma schema loaded from prisma\schema.prisma
Datasource "sqlite": SQLite database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   |
 2 |   provider          = "sqlite"
 3 |   url               = env("DATABASE_URL")
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.10.2

**Comment by sugarforever** [comment]
> E:\chat-ollama\chat-ollama-main>npm run prisma-migrate
> 
> > prisma-migrate
> > prisma migrate dev
> 
> Prisma schema loaded from prisma\schema.prisma Datasource "sqlite": SQLite database
> 
> Error: Prisma schema validation - (get-config wasm) Error code: P1012 error: Environment variable not found: DATABASE_URL. --> schema.prisma:3 | 2 | provider = "sqlite" 3 | url = env("DATABASE_URL") |
> 
> Validation Error Count: 1 [Context: getConfig]
> 
> Prisma CLI Version : 5.10.2

看来我必须要更新下文档了。

这个问题是因为没有环境变量DATABASE_URL

参考以下 `.env.example` ，在你的E:\chat-ollama\chat-ollama-main下创建一个 `.env` 文件。.env 文件中的 `DATABASE_URL` 可以设置为你期望放置sqlite文件的路径。

```
DISABLE_VERCEL_ANALYTICS=false
OPENAI_API_KEY=
DATABASE_URL=/Users/xyz/private/chatollama.sqlite
```

**Comment by izonewonyoung** [comment]
问题解决了，感谢^^

**Comment by izonewonyoung** [comment]
构建Knowledge Base的时候出现问题
Created knowledge base hj3: [object Object]
Warning: TT: undefined function: 32
Warning: TT: undefined function: 3
[nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
  at Chroma.ensureCollection (/E:/chat-ollama/chat-ollama-main/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Chroma.fromExistingCollection (/E:/chat-ollama/chat-ollama-main/node_modules/@langchain/community/dist/vectorstores/chroma.js:274:9)
  at ingestDocument (E:\chat-ollama\chat-ollama-main\server\api\knowledgebases\index.post.ts:25:1)
  at Object.handler (E:\chat-ollama\chat-ollama-main\server\api\knowledgebases\index.post.ts:92:1)
  at async Object.handler (/E:/chat-ollama/chat-ollama-main/node_modules/h3/dist/index.mjs:1962:19)
  at async Server.toNodeHandle (/E:/chat-ollama/chat-ollama-main/node_modules/h3/dist/index.mjs:2249:7)
另外，已经构建的Knowledge Base怎么删除啊。。。

**Comment by Yamcanda** [comment]
我也一样 500 Chroma getOrCreateCollection error fetch failed.

**Comment by Yamcanda** [comment]
我的是在 server\api\models\chat\index.post.ts 第 50 行左右的 new Chroma 中增加 url 参数指向 chromadb 地址可以解决。
你这样应该是在 server\api\knowledgebases\index.post.ts 给 chromedb 设置 url 参数，应该是 dbConfig 变量里面

**Comment by jiyzhang** [comment]
`DATABASE_URL="file:/Users/xyz/private/chatollama.sqlite"`

> npm run prisma-migrate
> 
> > prisma-migrate
> > prisma migrate dev
> 
> Environment variables loaded from .env
> Prisma schema loaded from prisma/schema.prisma
> Datasource "sqlite": SQLite database
> 
> Error: Prisma schema validation - (get-config wasm)
> Error code: P1012
> error: Error validating datasource `sqlite`: the URL must start with the protocol `file:`.
>   -->  schema.prisma:3
>    |
>  2 |   provider          = "sqlite"
>  3 |   url               = env("DATABASE_URL")
>    |
> 
> Validation Error Count: 1
> [Context: getConfig]
> 
> Prisma CLI Version : 5.10.2

**Comment by xiaojiegogogo** [comment]
我也遇到这个问题

**Comment by satrong** [comment]
@jiyzhang  @xiaojiegogogo 

`DATABASE_URL="file:/Users/xyz/private/chatollama.sqlite"`

这个是 demo 地址，可能你电脑实际上没有这个文件路径，可以将配置改成：

```
DATABASE_URL=file:../../chatollama.sqlite
```

然后再执行：

```
npm run prisma-migrate
```

**Comment by xiaojiegogogo** [comment]
> @jiyzhang @xiaojiegogogo
> 
> `DATABASE_URL="file:/Users/xyz/private/chatollama.sqlite"`
> 
> 是demo地址，可能你电脑上实际上没有这个文件路径，可以将配置改成：
> 
> ```
> DATABASE_URL=file:../../chatollama.sqlite
> ```
> 
> 然后再执行：
> 
> ```
> npm run prisma-migrate
> ```

嗯嗯，是可以了，我想知道我怎么默认模型啊，就不选择了，先来个默认的

**Comment by izonewonyoung** [comment]
> 我的是在 server\api\models\chat\index.post.ts 第 50 行左右的 new Chroma 中增加 url 参数指向 chromadb 地址可以解决。 你这样应该是在 server\api\knowledgebases\index.post.ts 给 chromedb 设置 url 参数，应该是 dbConfig 变量里面
![image](https://github.com/sugarforever/chat-ollama/assets/144020313/51468d48-0acb-4a78-95ac-d16c6f13a939)
请问具体应该如何操作呢

**Comment by izonewonyoung** [comment]
> @izonewonyoung 可以打开浏览器访问一下 http://localhost:8000/ 看看能否连通，正常情况如下图：
> 
> ![图片](https://private-user-images.githubusercontent.com/5283258/311437295-93f1431a-7328-4f68-a1ac-d60e578dfc03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODg3MjksIm5iZiI6MTcwOTk4ODQyOSwicGF0aCI6Ii81MjgzMjU4LzMxMTQzNzI5NS05M2YxNDMxYS03MzI4LTRmNjgtYTFhYy1kNjBlNTc4ZGZjMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMTI0NzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGIxZDNjMDUwNDIxMDg4NWRlMGVjNzA0ZGM0Zjk2YWExZDBkZTVjMjAzYjBmZDgyNzg0ZjFjMmQyYjc0OGFhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pi0NWQk5hJ3_1lbYS93D2wHnKC8ametp15w8B7U8IqI)
> 
> 如果不能访问，有可能是你的 ChromaDB 端口（默认就是8000）问题，也有可能是 ChromaDB 没有正常运行

![image](https://github.com/sugarforever/chat-ollama/assets/144020313/103c155d-154f-4a37-8938-8265fd7e87c5)
应该怎么解决呢？

**Comment by izonewonyoung** [comment]
> 如果没有安装 ChromaDB ，先安装 docker ，再执行下面命令：
> 
> ```
> docker pull chromadb/chroma
> docker run -d -p 8000:8000 chromadb/chroma
> ```

问题解决了，十分感谢！！！^^
