### ISSUE TITLE
[bug] redis-parser出错

### ISSUE THREAD

**Issue by meokey** [sugarforever/chat-ollama#122]
我试了试在docker的环境变量中加了REDIS_HOST指向独立的REDIS地址IP，然后chat没有问题，但是knowledge base对话没有回应，看了看logs，有下面的错误信息滚动重复：

[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[nuxt] [request error] [unhandled] [500] Protocol error, got "H" as reply type byte. Please report this.
  at handleError (./.output/server/node_modules/redis-parser/lib/parser.js:190:15)  
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/app/.output/server/node_modules/redis-parser/lib/parser.js:304:14)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)
[ioredis] Unhandled error event: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/app/.output/server/node_modules/redis-parser/lib/parser.js:190:15)

**Comment by sugarforever** [comment]
你的Redis是跑在TLS上的吗？参考https://github.com/redis/ioredis/issues/1862

**Comment by meokey** [comment]
搞定。谢谢指导~
