### ISSUE TITLE
最新Docker版本无法创建instructions

### ISSUE THREAD

**Issue by xiaoxinpro** [sugarforever/chat-ollama#168]
docker版本：0001coder/chatollama:latest [[4fac882fc86f](https://hub.docker.com/layers/0001coder/chatollama/latest/images/sha256-4fac882fc86fb17b1e198f5f37bcf1ae590af239e340a45ba1030f3f1e2336f5?context=explore)]

docker-compose文件： https://github.com/sugarforever/chat-ollama/blob/main/docker-compose.yaml

在`instructions`页面` Create New Instruction ` 按钮点击无任何反应。

当打开`instructions`页面时（没有点击按钮），控制台报错如下：

```
DadukHvB.js:19 TypeError: Cannot read properties of null (reading 'map')
    at 2AyNaVJS.js:1:635
    at ys.fn (DadukHvB.js:15:9107)
    at ys.run (DadukHvB.js:15:1517)
    at get value (DadukHvB.js:15:9352)
    at ru (DadukHvB.js:15:1689)
    at get dirty (DadukHvB.js:15:1236)
    at B.h.update (DadukHvB.js:19:39811)
    at St (DadukHvB.js:19:46)
    at ra (DadukHvB.js:19:1756)
```

![image](https://github.com/sugarforever/chat-ollama/assets/11443745/e0c73fb8-9ad2-449f-a38f-4d9a3cfedf67)

**Comment by satrong** [comment]
可以看下 docker 有没有输出错误日志，有可能是数据库没有初始化

**Comment by xiaoxinpro** [comment]
@satrong  docker 日志如下：

```
chatollama-1  | Listening on http://[::]:3000
chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama-1  | Error fetching instructions:  PrismaClientKnownRequestError: 
chatollama-1  | Invalid `prisma.instruction.findMany()` invocation:
chatollama-1  | 
chatollama-1  | 
chatollama-1  | The table `main.Instruction` does not exist in the current database.
chatollama-1  |     at In.handleRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6854)
chatollama-1  |     at In.handleAndLogRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6188)
chatollama-1  |     at In.request (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:5896)
chatollama-1  |     at async l (/app/.output/server/node_modules/@prisma/client/runtime/library.js:127:10871)
chatollama-1  |     at async listInstructions (file:///app/.output/server/chunks/routes/api/index.get.mjs:13:12)
chatollama-1  |     at async Object.handler (file:///app/.output/server/chunks/routes/api/index.get.mjs:20:24)
chatollama-1  |     at async Object.handler (file:///app/.output/server/chunks/runtime.mjs:2919:19)
chatollama-1  |     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3185:7) {
chatollama-1  |   code: 'P2021',
chatollama-1  |   clientVersion: '5.11.0',
chatollama-1  |   meta: { modelName: 'Instruction', table: 'main.Instruction' }
chatollama-1  | }
chatollama-1  | Ollama:  {
chatollama-1  |   host: 'http://host.docker.internal:11434',
chatollama-1  |   username: null,
chatollama-1  |   password: null
chatollama-1  | }
chatollama-1  | Ollama:  {
chatollama-1  |   host: 'http://host.docker.internal:11434',
chatollama-1  |   username: null,
chatollama-1  |   password: null
chatollama-1  | }
chatollama-1  | Authorization: bnVsbDpudWxs
chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama-1  | Error fetching instructions:  PrismaClientKnownRequestError: 
chatollama-1  | Invalid `prisma.instruction.findMany()` invocation:
chatollama-1  | 
chatollama-1  | 
chatollama-1  | The table `main.Instruction` does not exist in the current database.
chatollama-1  |     at In.handleRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6854)
chatollama-1  |     at In.handleAndLogRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6188)
chatollama-1  |     at In.request (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:5896)
chatollama-1  |     at async l (/app/.output/server/node_modules/@prisma/client/runtime/library.js:127:10871)
chatollama-1  |     at async listInstructions (file:///app/.output/server/chunks/routes/api/index.get.mjs:13:12)
chatollama-1  |     at async Object.handler (file:///app/.output/server/chunks/routes/api/index.get.mjs:20:24)
chatollama-1  |     at async Object.handler (file:///app/.output/server/chunks/runtime.mjs:2919:19)
chatollama-1  |     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3185:7) {
chatollama-1  |   code: 'P2021',
chatollama-1  |   clientVersion: '5.11.0',
chatollama-1  |   meta: { modelName: 'Instruction', table: 'main.Instruction' }
chatollama-1  | }
chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama-1  | Error fetching instructions:  PrismaClientKnownRequestError: 
chatollama-1  | Invalid `prisma.instruction.findMany()` invocation:
chatollama-1  | 
chatollama-1  | 
chatollama-1  | The table `main.Instruction` does not exist in the current database.
chatollama-1  |     at In.handleRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6854)
chatollama-1  |     at In.handleAndLogRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6188)
chatollama-1  |     at In.request (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:5896)
chatollama-1  |     at async l (/app/.output/server/node_modules/@prisma/client/runtime/library.js:127:10871)
chatollama-1  |     at async listInstructions (file:///app/.output/server/chunks/routes/api/index.get.mjs:13:12)
chatollama-1  |     at async Object.handler (file:///app/.output/server/chunks/routes/api/index.get.mjs:20:24)
chatollama-1  |     at async Object.handler (file:///app/.output/server/chunks/runtime.mjs:2919:19)
chatollama-1  |     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3185:7) {
chatollama-1  |   code: 'P2021',
chatollama-1  |   clientVersion: '5.11.0',
chatollama-1  |   meta: { modelName: 'Instruction', table: 'main.Instruction' }
chatollama-1  | }
```

**Comment by satrong** [comment]
还真是数据库的问题，你试试在 docker 里面执行一下 `pnpm prisma-migrate`

**Comment by xiaoxinpro** [comment]
可以了，非常感谢。

```
# pnpm prisma-migrate

> nuxt-app@ prisma-migrate /app
> prisma migrate dev

Prisma schema loaded from prisma/schema.prisma
Datasource "sqlite": SQLite database "chatollama.sqlite" at "file:/app/sqlite/chatollama.sqlite"

Applying migration `20240302004128_init`
Applying migration `20240305202320_knowlegebase_files`
Applying migration `20240305205052_files_cascade_deletion`
Applying migration `20240309101210_instruction`

The following migration(s) have been applied:

migrations/
  └─ 20240302004128_init/
    └─ migration.sql
  └─ 20240305202320_knowlegebase_files/
    └─ migration.sql
  └─ 20240305205052_files_cascade_deletion/
    └─ migration.sql
  └─ 20240309101210_instruction/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (v5.11.0) to ./node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client in 9
9ms
```
