### ISSUE TITLE
[bug] Invalid string length on creating Knowledge Base via Chroma

### ISSUE THREAD

**Issue by meokey** [sugarforever/chat-ollama#191]
maybe I'm uploading too many files (24 pdf files)?

```Created knowledge base xxxxxxxxxxxxxxxxxx: 9
Creating embeddings for OpenAI model: text-embedding-3-small, host: keys.x_openai_api_host
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options:  {
  host: 'xxx.xxx.xxx.xxx',
  port: 6379,
  username: undefined,
  password: undefined
}
[nuxt] [request error] [unhandled] [500] Invalid string length
  at JSON.stringify (<anonymous>)  
  at Object.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:724:44)  
  at Object.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:1321:72)  
  at ApiApi.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:1568:41)  
  at Collection.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:1883:37)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Chroma.addVectors (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:145:9)  
  at async ParentDocumentRetriever.addDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)  
  at async ingestDocument (./.output/server/chunks/routes/api/index.post2.mjs:42:3)  
  at async Object.handler (./.output/server/chunks/routes/api/index.post2.mjs:120:5)
```

**Comment by sugarforever** [comment]
> text-embedding-3-small

I managed to create a knowledge base with 58 PDF files.
<img width="1228" alt="Screenshot 2024-04-03 at 1 06 42 AM" src="https://github.com/sugarforever/chat-ollama/assets/404421/45e1343c-481a-40c6-9262-d7f5cea255c5">

Could you please try again and see if the issue is reproducible?

**Comment by sugarforever** [comment]
> Invalid string length

Btw, how big is your file package in total?

**Comment by sugarforever** [comment]
Alternatively, could you please try if `Milvus` can mitigate this problem?

You could switch to Milvus by - https://github.com/sugarforever/chat-ollama?tab=readme-ov-file#supported-vector-databases

```
# Supported values: chroma, milvus
VECTOR_STORE=milvus
MILVUS_URL=http://localhost:19530
```

**Comment by meokey** [comment]
****

> > Invalid string length
> 
> Btw, how big is your file package in total?

all PDF files, around 40MB in total, max file size is 9MB.

**Comment by meokey** [comment]
> > text-embedding-3-small
> 
> I managed to create a knowledge base with 58 PDF files. 
> 
> Could you please try again and see if the issue is reproducible?

I tried again and this time it throws a short error message as below:

```
Created knowledge base xxxxxxxxxxxxxx: 10
Warning: TT: undefined function: 32
Warning: TT: undefined function: 32
Creating embeddings for OpenAI model: text-embedding-3-small, host: keys.x_openai_api_host
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options:  {
  host: 'xxxxxxxxxxxxxx',
[nuxt] [request error] [unhandled] [500] Invalid string length
  at JSON.stringify (<anonymous>)  
```

I will try milvus when I get a sec next time
