### ISSUE TITLE
报错了能帮我看一下？是什么问题

### ISSUE THREAD

**Issue by yongjizhao** [sugarforever/chat-ollama#199]
ERROR  [nuxt] [request error] [unhandled] [500] 
Invalid prisma.knowledgeBase.count() invocation in
/Users/yongjizhao/Documents/chat-ollama/server/api/knowledgebases/index.post.ts:98:1

  95   }
  96 }
  97 
→ 98 const exist = await prisma.knowledgeBase.count(
Error querying the database: Error code 14: Unable to open the database file
  at In.handleRequestError (./node_modules/@prisma/client/runtime/library.js:122:7154)  
  at In.handleAndLogRequestError (./node_modules/@prisma/client/runtime/library.js:122:6188)  
  at In.request (./node_modules/@prisma/client/runtime/library.js:122:5896)  
  at async l (./node_modules/@prisma/client/runtime/library.js:127:10871)  
  at Object.handler (./server/api/knowledgebases/index.post.ts:98:1)  
  at async ./node_modules/h3/dist/index.mjs:1962:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)

**Comment by yongjizhao** [comment]
我Ollama Server Setting 如果选用 http://127.0.0.1:11434可以选择到models 如果用docker地址却看不到
