### ISSUE TITLE
为什么我用docker-compose启动不起来，它无法连接到本地的Ollama,ollama已经启动，curl它是可以。

### ISSUE THREAD

**Issue by iaoxuesheng** [sugarforever/chat-ollama#200]
chatollama_1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama_1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama_1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama_1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama_1  | Error fetching instructions:  PrismaClientKnownRequestError: 
chatollama_1  | Invalid `prisma.instruction.findMany()` invocation:
chatollama_1  | 
chatollama_1  | 
chatollama_1  | The table `main.Instruction` does not exist in the current database.
chatollama_1  |     at In.handleRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6854)
chatollama_1  |     at In.handleAndLogRequestError (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:6188)
chatollama_1  |     at In.request (/app/.output/server/node_modules/@prisma/client/runtime/library.js:122:5896)
chatollama_1  |     at async l (/app/.output/server/node_modules/@prisma/client/runtime/library.js:127:10871)
chatollama_1  |     at async listInstructions (file:///app/.output/server/chunks/routes/api/index.get.mjs:13:12)
chatollama_1  |     at async Object.handler (file:///app/.output/server/chunks/routes/api/index.get.mjs:20:24)
chatollama_1  |     at async Object.handler (file:///app/.output/server/chunks/runtime.mjs:2919:19)
chatollama_1  |     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3185:7) {
chatollama_1  |   code: 'P2021',
chatollama_1  |   clientVersion: '5.11.0',
chatollama_1  |   meta: { modelName: 'Instruction', table: 'main.Instruction' }
chatollama_1  | }

**Comment by recall704** [comment]
如果你的 ollama 不在 docker-compose 内启动，那是不能使用 127.0.0.1 访问的，你可以配置 IP 为本机试试

```
OLLAMA_HOST=192.168.0.10 ollama serve
```

**Comment by iaoxuesheng** [comment]
ollama是自启动的吗，这个怎么取消掉，在执行时显示端口占有，kill掉会又被占有，感觉一直在自启动

> 如果你的 ollama 不在 docker-compose 内启动，那是不能使用 127.0.0.1 访问的，你可以配置 IP 为本机试试
> 
> ```
> OLLAMA_HOST=192.168.0.10 ollama serve
> ```

**Comment by iaoxuesheng** [comment]
> 如果你的 ollama 不在 docker-compose 内启动，那是不能使用 127.0.0.1 访问的，你可以配置 IP 为本机试试
> 
> ```
> OLLAMA_HOST=192.168.0.10 ollama serve
> ```
您好，感谢您的回复，我的docker-compose.yaml文件是这样：version: '3.1'
services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - chromadb_data:/chroma/.chroma/index

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - OLLAMA_URL=http://192.168.59.273:11434
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
    image: 0001coder/chatollama:latest
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/.chatollama:/app/sqlite

volumes:
  chromadb_data:               然后也在配置了IP为本机，但是在chatollama里面好像还是在访问localhost：11434，然后还是报错找不到ollama

**Comment by sugky7302** [comment]
如果 ollama 建置在本機的話，或許您可以使用 http://host.docker.internal:11434 來跳轉，這是 docker 提供容器連線到宿主機的特定 dns，可以參考看看。

**Comment by pake35** [comment]
In the Readme. have solution: 
host:
http://host.docker.internal:11434/

**Comment by satrong** [comment]
我今天弄好了好久，使用 http://host.docker.internal:11434/ 也不行。

我的解决方法：

如果是 docker 启动的 chat-ollama 出现这种问题，可以修改 ollama 服务绑定的 ip 为 `0.0.0.0`，然后在 chat-ollama 里面的 settings 里面配置 `http://[宿主机局域网ip]:11434`。
具体修改 ollama 绑定 ip 的方法可参考官方文档：https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server

**Comment by iwangbowen** [comment]
设置里面的`host`应该配置为http://host.docker.internal:11434/

**Comment by satrong** [comment]
参考一下这个 issue

https://github.com/sugarforever/chat-ollama/issues/200#issuecomment-2041797807

**Comment by anynone** [comment]
> 我今天弄好了好久，使用 http://host.docker.internal:11434/ 也不行。
> 
> 我的解决方法：
> 
> 如果是 docker 启动的 chat-ollama 出现这种问题，可以修改 ollama 服务绑定的 ip 为 `0.0.0.0`，然后在 chat-ollama 里面的 settings 里面配置 `http://[宿主机局域网ip]:11434`。 具体修改 ollama 绑定 ip 的方法可参考官方文档：https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server

如果是docker部署，docker inspect network ls  看docker的虚拟网络，然后 docker inspect network 网络名称 查看网段，我这里是18网段， 所以配置成http://172.18.0.1:11434  。 防火墙配置源地址172.18.0.0/16 任意端口访问 172.18.0.0/16  11434端口保证安全性

**Comment by sugarforever** [comment]
> > 我今天弄好了好久，使用 http://host.docker.internal:11434/ 也不行。
> > 我的解决方法：
> > 如果是 docker 启动的 chat-ollama 出现这种问题，可以修改 ollama 服务绑定的 ip 为 `0.0.0.0`，然后在 chat-ollama 里面的 settings 里面配置 `http://[宿主机局域网ip]:11434`。 具体修改 ollama 绑定 ip 的方法可参考官方文档：https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server
> 
> 如果是docker部署，docker inspect network ls 看docker的虚拟网络，然后 docker inspect network 网络名称 查看网段，我这里是18网段， 所以配置成http://172.18.0.1:11434 。 防火墙配置源地址172.18.0.0/16 任意端口访问 172.18.0.0/16 11434端口保证安全性

非常具有实战意义的反馈。有兴趣将其写成 README.md 文档的一个章节吗？可以以PR的形式提交。
