### ISSUE TITLE
[bug] 更新knowledge base出错

### ISSUE THREAD

**Issue by meokey** [sugarforever/chat-ollama#212]
···
Ollama:  { host: 'http://192.168.0.100:11434', username: null, password: null }
[Vue Router warn]: No match found for location with path "/api/knowledgebases/12"
···

但是12是我刚刚生成的knowledge base
![CTMS 2024-04-05 09_38_26-Arc](https://github.com/sugarforever/chat-ollama/assets/956787/6da2b8ee-5cb1-469a-a138-53ca7f7763b4)

PS. 在chat里也可以查询这个知识库的内容。

**Comment by satrong** [comment]
与 #201 一样的问题

**Comment by meokey** [comment]
#201

**Comment by meokey** [comment]
sorry I have to re-open the issue - I notice an PR has been merged and pulled the latest image, however it throws error message like below:

```
Ollama:  { host: 'http://xxx.xxx.xxx.xxx:11434', username: null, password: null }
Knowledge base ID:  12
Ollama:  { host: 'http://xxx.xxx.xxx.xxx:11434', username: null, password: null }
Update knowledge base xxxxxxxxxxxxxxxxxxx with ID 12
Creating embeddings for OpenAI model: text-embedding-3-small, host: keys.x_openai_api_host
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options:  {
  host: 'xxx.xxx.xxx.xxx',
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Object.upsert (file:///app/.output/server/node_modules/chromadb/dist/chromadb.mjs:724:44)
    at Object.upsert (file:///app/.output/server/node_modules/chromadb/dist/chromadb.mjs:1321:72)
    at ApiApi.upsert (file:///app/.output/server/node_modules/chromadb/dist/chromadb.mjs:1568:41)
    at Collection.upsert (file:///app/.output/server/node_modules/chromadb/dist/chromadb.mjs:1883:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Chroma.addVectors (file:///app/.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:145:9)
    at async ParentDocumentRetriever.addDocuments (file:///app/.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)
[nuxt] [request error] [unhandled] [500] Invalid string length
  at JSON.stringify (<anonymous>)  
  at Object.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:724:44)  
  at Object.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:1321:72)  
  at ApiApi.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:1568:41)  
  at Collection.upsert (./.output/server/node_modules/chromadb/dist/chromadb.mjs:1883:37)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Chroma.addVectors (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:145:9)  
  at async ParentDocumentRetriever.addDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)  
  at async ingestDocument (./.output/server/chunks/_/http.mjs:34:3)  
  at async Object.handler (./.output/server/chunks/routes/api/knowledgebases/_id_.put.mjs:72:5)
```

**Comment by meokey** [comment]
Vue，http server 对 upload 文件的大小和数量有限制吗？

**Comment by sugarforever** [comment]
根据我的测试，50个文件是没有问题的。关于大小，我还没有测试，我周末试试
