### ISSUE TITLE
无法建立知识库，选择URL 点击保存出错

### ISSUE THREAD

**Issue by nuaadupuliu** [sugarforever/chat-ollama#230]
在本地用docker搭好chat-ollama后，选择外部网址URL https://github.com/jonfairbanks/local-rag 建立知识库出错。

![image](https://github.com/sugarforever/chat-ollama/assets/5336788/321940e6-568e-4e95-bc2e-dcea2d698c14)

`chatollama-1  | Created knowledge base Test: 1
chatollama-1  | Creating embeddings for Ollama served model: mxbai-embed-large
chatollama-1  | Creating Chroma vector store
chatollama-1  | Initializing vector store retriever
chatollama-1  | 0 documents added to collection collection_1.
chatollama-1  | URL:  https://github.com/jonfairbanks/local-rag
chatollama-1  | [nuxt] [request error] [unhandled] [500] Failed to launch the browser process!
chatollama-1  | /root/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
chatollama-1  | 
chatollama-1  | 
chatollama-1  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
chatollama-1  | 
chatollama-1  |   at onClose (./.output/server/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:270:20)  
chatollama-1  |   at Interface.<anonymous> (./.output/server/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:258:24)  
chatollama-1  |   at Interface.emit (node:events:526:35)  
chatollama-1  |   at Interface.close (node:internal/readline/interface:527:10)  
chatollama-1  |   at Socket.onend (node:internal/readline/interface:253:10)  
chatollama-1  |   at Socket.emit (node:events:526:35)  
chatollama-1  |   at endReadableNT (node:internal/streams/readable:1376:12)  
chatollama-1  |   at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
`
请问这个怎么解决，谢谢

**Comment by doriszhang2020** [comment]
同问保存url或者更新知识库时（无法更新知识库），提示/root/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared ``libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by MasonLi** [comment]
同问
