### ISSUE TITLE
在Google colab中部署后，可以和大模型chat，但是新建知识库时，上传的文档会卡住无法保存并报错

### ISSUE THREAD

**Issue by Wcoke9527** [sugarforever/chat-ollama#24]
报错：Ollama:  { host: 'null', username: 'null', password: 'null' }
Created knowledge base 平安: [object Object]
[nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
  at Chroma.ensureCollection (./node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Chroma.fromExistingCollection (./node_modules/@langchain/community/dist/vectorstores/chroma.js:274:9)  
  at ingestDocument (./server/api/knowledgebases/index.post.ts:25:1)  
  at Object.handler (./server/api/knowledgebases/index.post.ts:92:1)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1962:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)

在colab通过ngrok做了3000端口的url映射，和大模型直接对话没问题，但是创建知识库时没反应

**Comment by guoweiyu** [comment]
问题解决了吗

**Comment by sugarforever** [comment]
> 报错：Ollama: { host: 'null', username: 'null', password: 'null' } Created knowledge base 平安: [object Object] [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed at Chroma.ensureCollection (./node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Chroma.fromExistingCollection (./node_modules/@langchain/community/dist/vectorstores/chroma.js:274:9) at ingestDocument (./server/api/knowledgebases/index.post.ts:25:1) at Object.handler (./server/api/knowledgebases/index.post.ts:92:1) at async Object.handler (./node_modules/h3/dist/index.mjs:1962:19) at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
> 
> 在colab通过ngrok做了3000端口的url映射，和大模型直接对话没问题，但是创建知识库时没反应

看起来应该是Chroma的问题。你有运行Chroma吗？Chroma是运行在哪里的？
