### ISSUE TITLE
使用任何模型都报错[500] stream.getReader is not a function

### ISSUE THREAD

**Issue by Mr-wr** [sugarforever/chat-ollama#27]
使用 qwen:4b模型报错[500] stream.getReader is not a function
[
 Document {
    pageContent: '*********\n' +
      '49\n' +
      '****\n' +
      *****\n' +
      '*****\n' +
      '【******\n' +
      '*******\n' +
      '【*********************】',
    metadata: { blobType: 'application/pdf', source: 'blob', loc: [Object] }
  }
]
<ref *1> IterableReadableStream [ReadableStream] {
  _state: 'readable',
  _reader: undefined,
  _storedError: undefined,
  _disturbed: false,
  _readableStreamController: ReadableStreamDefaultController {
    _controlledReadableStream: [Circular *1],
    _queue: SimpleQueue {
      _cursor: 0,
      _size: 0,
      _front: [Object],
      _back: [Object]
    },
    _queueTotalSize: 0,
    _started: true,
    _closeRequested: false,
    _pullAgain: false,
    _pulling: true,
    _strategySizeAlgorithm: [Function (anonymous)],
    _strategyHWM: 1,
    _pullAlgorithm: [Function: pullAlgorithm],
    _cancelAlgorithm: [Function: cancelAlgorithm]
  },
  reader: undefined
}
[nuxt] [request error] [unhandled] [500] stream.getReader is not a function
  at Function.fromReadableStream (chat-ollama/node_modules/@langchain/core/dist/utils/stream.js:68:31)
  at createOllamaStream (chat-ollama/node_modules/@langchain/community/dist/utils/ollama.js:36:43)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async createOllamaChatStream (chat-ollama/node_modules/@langchain/community/dist/utils/ollama.js:57:5)
  at async ChatOllama._streamResponseChunks (chat-ollama/node_modules/@langchain/community/dist/chat_models/ollama.js:396:30)
  at async ChatOllama._streamIterator (chat-ollama/node_modules/@langchain/core/dist/language_models/chat_models.js:78:34)
  at async ChatOllama.transform (chat-ollama/node_modules/@langchain/core/dist/runnables/base.js:337:9)
  at async wrapInputForTracing (chat-ollama/node_modules/@langchain/core/dist/runnables/base.js:231:30)
  at async pipeGeneratorWithSetup (chat-ollama/node_modules/@langchain/core/dist/utils/stream.js:223:19)
  at async StringOutputParser._transformStreamWithConfig (chat-ollama/node_modules/@langchain/core/dist/runnables/base.js:252:26)

**Comment by satrong** [comment]
你的 nodejs 是多少版本的？应该需要 18.0.0+

**Comment by Mr-wr** [comment]
> 你的 nodejs 是多少版本的？应该需要 18.0.0+

哦，非常感谢，解决了，确实是nodejs版本问题，我已经升级到了v20.11.1

**Comment by sugarforever** [comment]
Closing as the issue has been addressed.
