### ISSUE TITLE
跟着视频使用groq里面的llama3,但发现接口返回数据有问题，不能显示回复

### ISSUE THREAD

**Issue by pamxy** [sugarforever/chat-ollama#319]
clone了master的代码,直接无ollama跑了起来，然后配置groq,一切都就绪,发送了一个Hello,结果没回应,F12发现返回403,然后直接groq官网看到可以curl调用,我直接改成postman调用groq的API,可成功调用，是否groq的API接口变动了导致chatollama调用不通？🥶
入参
`{
  "model": "llama3-70b-8192",
  "family": "Groq",
  "messages": [
    {
      "role": "user",
      "id": 13,
      "content": "Hello",
      "timestamp": 1713608739048
    }
  ],
  "stream": true
}`

返回参数
`{
    "url": "/api/models/chat",
    "statusCode": 403,
    "statusMessage": "",
    "message": "403 <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> groq.com</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">xxxxxxxxxx</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">xxx.xxx.xxx.xxx</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>

</body>
</html>
",
    "stack": "<pre><span class="stack"><p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p></span>
<span class="stack"><h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2></span>
<span class="stack"><p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p></span>
<span class="stack internal">at Function.generate (D:\Work\ai\chat-ollama\node_modules\.pnpm\groq-sdk@0.3.2\node_modules\groq-sdk\src\error.ts:66:14)</span>
<span class="stack internal">at Groq.makeStatusError (D:\Work\ai\chat-ollama\node_modules\.pnpm\groq-sdk@0.3.2\node_modules\groq-sdk\src\core.ts:383:21)</span>
<span class="stack internal">at Groq.makeRequest (D:\Work\ai\chat-ollama\node_modules\.pnpm\groq-sdk@0.3.2\node_modules\groq-sdk\src\core.ts:446:24)</span>
<span class="stack internal">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>
<span class="stack internal">at async RetryOperation._fn (D:\Work\ai\chat-ollama\node_modules\.pnpm\p-retry@4.6.2\node_modules\p-retry\index.js:50:12)</span></pre>"
}`

**Comment by luckbinle** [comment]
我也遇到这个问题

**Comment by luckbinle** [comment]
科学上网了，我自己写的python代码是可以用groq的。

**Comment by satrong** [comment]
那可能没有代理到。我正在尝试集成一个代理功能

**Comment by satrong** [comment]
正常现象

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/257597ba-6dca-4327-b248-531a38cd4ae8)

**Comment by luckbinle** [comment]
哈哈哈😂，好吧

**Comment by kentonson** [comment]
我在另一个翻译软件的插件里面测试也是这样的，我使用curl测试的结果跟你这个返回的一样，python代码运行正常，我在colab里面测试curl也是正常的

**Comment by kentonson** [comment]
兄弟，解决了麻烦提供下思路

**Comment by satrong** [comment]
已增加代理功能，可以尝试体验一下

**Comment by sugarforever** [comment]
> 已增加代理功能，可以尝试体验一下

关于代理的文档部分随后跟上
