### ISSUE TITLE
创建knowledge base 500 错误

### ISSUE THREAD

**Issue by lesca** [sugarforever/chat-ollama#32]
Hello,
我已经搜索过 issue 中关于500的文章，没有找到类似的。

我的错误如下：

```
Created knowledge base test3: [object Object]
[nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:13737:13
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async OllamaEmbeddings._request (./node_modules/@langchain/community/dist/embeddings/ollama.js:107:26)
  at async RetryOperation._fn (./node_modules/p-retry/index.js:50:12)
```

可见，knowledge base test3 创建之后报错了。

**环境信息**
* chat-ollama 克隆了 2024年3月10日 的版本
* chat 功能正常
* chromadb 端口 8000，可以访问
  * 浏览器直接访问，返回内容 `"detail": "Not Found"`
* 尝试过删除 sqlite 数据库并重建，删除 chromadb container 并重建，仍然报错

**Comment by wenjun-he** [comment]
同样出现这个问题，你是用docker起的吗？

**Comment by okey-dokey** [comment]
相同問題 我是用docker起的

**Comment by wenjun-he** [comment]
我这边试了docker和非docker的方案都会存在这个问题，哪位大佬可以看看这个问题？

**Comment by sugarforever** [comment]
有下载模型nomic-embed-text吗？

**Comment by lesca** [comment]
> 有下载模型nomic-embed-text吗？

有下载，按照视频的方法做的

```output
>ollama list
NAME                    ID              SIZE    MODIFIED
gemma:2b                b50d6c999e59    1.7 GB  2 weeks ago
gemma:7b                430ed3535049    5.2 GB  2 weeks ago
gemma:latest            430ed3535049    5.2 GB  2 weeks ago
llava:latest            8dd30f6b0cb1    4.7 GB  6 days ago
llava-cn:latest         d58b632b856a    4.7 GB  6 days ago
nomic-embed-text:latest 0a109f422b47    274 MB  7 days ago
qwen:14b                80362ced6553    8.2 GB  3 days ago
qwen:4b                 d53d04290064    2.3 GB  3 days ago
qwen:latest             d53d04290064    2.3 GB  3 days ago
qwen-yi:latest          e21f7ef28a0f    8.2 GB  2 days ago
```
