### ISSUE TITLE
重启服务后，知识库加载不出来，新增知识库失败

### ISSUE THREAD

**Issue by moffefei** [sugarforever/chat-ollama#327]
Chroma getOrCreateCollection error: Error: TypeError: fetch failed
![image](https://github.com/sugarforever/chat-ollama/assets/132885305/14ff21a0-799f-4898-bd6a-2f9cbd736883)

我是本地环境除了docker安装了ollama外，还直接安装了ollama客户端

**Comment by satrong** [comment]
方便提供一下服务端的报错吗？

**Comment by shenshiguan** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/61cd88ee-e130-4a98-bbee-facdb0e01c02)

我这也是，提交pdf文件 创建知识库

**Comment by moffefei** [comment]
> 方便提供一下服务端的报错吗？

刚又重试了一下，新增成功一个知识库
![image](https://github.com/sugarforever/chat-ollama/assets/132885305/9a1d8e5e-3d9a-46f2-b688-4ca91862088e)
但，访问这个知识库时报错：
`2024-04-22 23:19:22 chatollama-1  | User query:  什么是RAG
2024-04-22 23:19:27 chatollama-1  | [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
2024-04-22 23:19:27 chatollama-1  |   at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)  
2024-04-22 23:19:27 chatollama-1  |   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
2024-04-22 23:19:27 chatollama-1  |   at async Chroma.similaritySearchVectorWithScore (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:187:28)  
2024-04-22 23:19:27 chatollama-1  |   at async Chroma.similaritySearch (./.output/server/node_modules/@langchain/core/dist/vectorstores.js:104:25)  
2024-04-22 23:19:27 chatollama-1  |   at async ParentDocumentRetriever._getRelevantDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:103:23)  
2024-04-22 23:19:27 chatollama-1  |   at async ParentDocumentRetriever.getRelevantDocuments (./.output/server/node_modules/@langchain/core/dist/retrievers/index.js:67:29)  
2024-04-22 23:19:27 chatollama-1  |   at async Object.handler (./.output/server/chunks/routes/api/models/index.post.mjs:72:27)  
2024-04-22 23:19:27 chatollama-1  |   at async Object.handler (./.output/server/chunks/runtime.mjs:2963:19)  
2024-04-22 23:19:27 chatollama-1  |   at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3229:7)
2024-04-22 23:19:43 chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }`

**Comment by sugarforever** [comment]
> Chroma getOrCreateCollection error: Error: TypeError: fetch failed ![image](https://private-user-images.githubusercontent.com/132885305/324221592-14ff21a0-799f-4898-bd6a-2f9cbd736883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTMxNjMsIm5iZiI6MTcxMzkxMjg2MywicGF0aCI6Ii8xMzI4ODUzMDUvMzI0MjIxNTkyLTE0ZmYyMWEwLTc5OWYtNDg5OC1iZDZhLTJmOWNiZDczNjg4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMjU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGZkMTVhNTY4MTUzZTc4MmVhZWVkM2FmZmM3NjM2ZWMyNTdhYmNhOTE5MDc1MmJhNDc5NGE3MDY4MWRhMDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qsDxFxtGKojoBLBgK7OKEup5KfOILH2rIO4rVzsQAQw)
> 
> 我是本地环境除了docker安装了ollama外，还直接安装了ollama客户端

@shenshiguan @moffefei 这个getOrCreateCollection的错误是来自Chromadb。请确认有正常运行chromadb。我看你们给到的错误信息，应该是运行的开发服务器吧？如果没有安装运行Chromadb，请参考 https://github.com/sugarforever/chat-ollama?tab=readme-ov-file#use-with-nuxt-3-development-server 的第二步。


如果是用的代码仓库的docker-compose.yaml，那么chroma应该是以容器化的方式运行的。请确认容器正常启动。

**Comment by moffefei** [comment]
> > Chroma getOrCreateCollection error: Error: TypeError: fetch failed ![image](https://private-user-images.githubusercontent.com/132885305/324221592-14ff21a0-799f-4898-bd6a-2f9cbd736883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTMxNjMsIm5iZiI6MTcxMzkxMjg2MywicGF0aCI6Ii8xMzI4ODUzMDUvMzI0MjIxNTkyLTE0ZmYyMWEwLTc5OWYtNDg5OC1iZDZhLTJmOWNiZDczNjg4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMjU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGZkMTVhNTY4MTUzZTc4MmVhZWVkM2FmZmM3NjM2ZWMyNTdhYmNhOTE5MDc1MmJhNDc5NGE3MDY4MWRhMDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qsDxFxtGKojoBLBgK7OKEup5KfOILH2rIO4rVzsQAQw)
> > 我是本地环境除了docker安装了ollama外，还直接安装了ollama客户端
> 
> @shenshiguan @moffefei 这个getOrCreateCollection的错误是来自Chromadb。请确认有正常运行chromadb。我看你们给到的错误信息，应该是运行的开发服务器吧？如果没有安装运行Chromadb，请参考 https://github.com/sugarforever/chat-ollama?tab=readme-ov-file#use-with-nuxt-3-development-server 的第二步。
> 
> 如果是用的代码仓库的docker-compose.yaml，那么chroma应该是以容器化的方式运行的。请确认容器正常启动。

删除docker里面chroma和chatolllama服务重新安装后，解决了问题。应该是docker里安装的ollama服务和本地ollama服务起冲突了
