### ISSUE TITLE
添加知识库时报错：jwt must be provided

### ISSUE THREAD

**Issue by zbulrush** [sugarforever/chat-ollama#356]
ERROR  Failed to verify extracted token: jwt must be provided

  at module.exports [as verify] (node_modules/jsonwebtoken/verify.js:60:17)
  at verifyToken (server/middleware/auth.ts:18:1)
  at Object.handler (server/middleware/auth.ts:30:1)
  at node_modules/h3/dist/index.mjs:1962:31
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2249:7)

**Comment by zmm1996** [comment]
遇到同样的问题


![image](https://github.com/sugarforever/chat-ollama/assets/40532959/c4b89c83-761d-459b-93ff-2b9856032f5d)

**Comment by sugarforever** [comment]
> ERROR Failed to verify extracted token: jwt must be provided
> 
> at module.exports [as verify] (node_modules/jsonwebtoken/verify.js:60:17) at verifyToken (server/middleware/auth.ts:18:1) at Object.handler (server/middleware/auth.ts:30:1) at node_modules/h3/dist/index.mjs:1962:31 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16) at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2249:7)

知识库的添加是否成功？

这个错误是关于用户登录和身份验证的。当未登录，或者用户登录后的JWT令牌过期，会有这个信息打印。这与知识库的创建应该没有关系。

**Comment by sugarforever** [comment]
PR https://github.com/sugarforever/chat-ollama/pull/407
