### ISSUE TITLE
添加知识库后台报错，前台依然显示，  [nuxt] [request error] [unhandled] [500] ID undefined not found.

### ISSUE THREAD

**Issue by zmm1996** [sugarforever/chat-ollama#360]
![image](https://github.com/sugarforever/chat-ollama/assets/40532959/6b6721f4-b60e-49c1-95dd-063ab2778c63)

![image](https://github.com/sugarforever/chat-ollama/assets/40532959/1442feff-aa7e-40e6-a8a8-17091e5710c9)

**日志信息**

":{"source":"《平凡的世界》.txt","blobType":"text/plain","loc":{"lines":{"from":10449,"to":10458}}}}
2024-04-25 14:49:59 1 documents added to collection collection_15.
2024-04-25 14:49:59 KnowledgeBaseFile with ID:  16
2024-04-25 14:49:59 Creating embeddings for Ollama served model: nomic-embed-text:latest
2024-04-25 14:49:59 Creating Chroma vector store
2024-04-25 14:49:59 Initializing ParentDocumentRetriever with RedisDocstore
2024-04-25 14:49:59 Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
2024-04-25 14:49:59 0 URLs added to collection collection_15.
2024-04-25 14:49:59 All URLs: Set(0) {}
2024-04-25 14:49:59 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 14:49:59     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 14:49:59     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 14:49:59     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 14:49:59     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 14:49:59     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 14:49:59     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 14:49:59 URL: /api/knowledgebases User: null
2024-04-25 14:49:59 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:10:36 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:10:36     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:10:36     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:10:36     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:10:36     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:10:36     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:10:36     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:10:36 URL: /api/models/ User: null
2024-04-25 15:10:36 Ollama:  {
2024-04-25 15:10:36   host: 'http://host.docker.internal:11434',
2024-04-25 15:10:36   username: null,
2024-04-25 15:10:36   password: null
2024-04-25 15:10:36 }
2024-04-25 15:10:36 Ollama:  {
2024-04-25 15:10:36   host: 'http://host.docker.internal:11434',
2024-04-25 15:10:36   username: null,
2024-04-25 15:10:36   password: null
2024-04-25 15:10:36 }
2024-04-25 15:10:36 Authorization: bnVsbDpudWxs
2024-04-25 15:10:36 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:10:36     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:10:36     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:10:36     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:10:36     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:10:36     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:10:36     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:10:36 URL: /api/knowledgebases/ User: null
2024-04-25 15:10:36 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:10:36 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:10:36     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:10:36     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:10:36     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:10:36     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:10:36     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:10:36     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:10:36 URL: /api/instruction/ User: null
2024-04-25 15:10:36 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:10:39 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:10:39     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:10:39     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:10:39     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:10:39     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:10:39     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:10:39     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:10:39 URL: /api/instruction/ User: null
2024-04-25 15:10:39 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:10:39 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:10:39     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:10:39     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:10:39     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:10:39     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:10:39     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:10:39     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:10:39 URL: /api/knowledgebases/ User: null
2024-04-25 15:10:39 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:10:39 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:10:39     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:10:39     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:10:39     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:10:39     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:10:39     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:10:39     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:10:39 URL: /api/models/ User: null
2024-04-25 15:10:39 Ollama:  {
2024-04-25 15:10:39   host: 'http://host.docker.internal:11434',
2024-04-25 15:10:39   username: null,
2024-04-25 15:10:39   password: null
2024-04-25 15:10:39 }
2024-04-25 15:10:39 Ollama:  {
2024-04-25 15:10:39   host: 'http://host.docker.internal:11434',
2024-04-25 15:10:39   username: null,
2024-04-25 15:10:39   password: null
2024-04-25 15:10:39 }
2024-04-25 15:10:39 Authorization: bnVsbDpudWxs
2024-04-25 15:11:07 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:11:07     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:11:07     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:11:07     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:11:07     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:11:07     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:11:07     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:11:07 URL: /api/instruction/ User: null
2024-04-25 15:11:07 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:16 URL: /api/instruction/4 User: null
2024-04-25 15:12:16 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:16 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:16     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:16     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:16     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:16     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:16     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:16 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:16     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:16     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:16     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:16     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:16     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:12:16     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:16 URL: /api/instruction/ User: null
2024-04-25 15:12:16 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:19 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:19     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:19     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:19     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:19     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:19     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:12:19     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:19 URL: /api/instruction/ User: null
2024-04-25 15:12:19 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:19 URL: /api/knowledgebases/ User: null
2024-04-25 15:12:19 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:19 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:19     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:19     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:19     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:19     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:19     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:12:19     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:20 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:20     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:20     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:20     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:20     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:20     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:12:20     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:20 URL: /api/instruction/ User: null
2024-04-25 15:12:20 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:20 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:20     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:20     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:20     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:20     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:20     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:12:20     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:20 URL: /api/knowledgebases/ User: null
2024-04-25 15:12:20 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-25 15:12:20 URL: /api/models/ User: null
2024-04-25 15:12:20 Ollama:  {
2024-04-25 15:12:20   host: 'http://host.docker.internal:11434',
2024-04-25 15:12:20   username: null,
2024-04-25 15:12:20   password: null
2024-04-25 15:12:20 }
2024-04-25 15:12:20 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:20     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:20     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:20     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:20     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:20     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-25 15:12:20     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:20 Ollama:  {
2024-04-25 15:12:20   host: 'http://host.docker.internal:11434',
2024-04-25 15:12:20   username: null,
2024-04-25 15:12:20   password: null
2024-04-25 15:12:20 }
2024-04-25 15:12:20 Authorization: bnVsbDpudWxs
2024-04-25 15:12:55 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-25 15:12:55     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-25 15:12:55     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6943:18)
2024-04-25 15:12:55     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6954:16)
2024-04-25 15:12:55     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:31)
2024-04-25 15:12:55     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-25 15:12:55 URL: /api/models/chat User: null
2024-04-25 15:12:55 Ollama:  {
2024-04-25 15:12:55   host: 'http://host.docker.internal:11434',
2024-04-25 15:12:55   username: null,
2024-04-25 15:12:55   password: null
2024-04-25 15:12:55 }
2024-04-25 15:12:55 Chat with knowledge base with id:  15
2024-04-25 15:12:55 Knowledge base 平凡的世界 with embedding "nomic-embed-text:latest"
2024-04-25 15:12:55 Creating embeddings for Ollama served model: nomic-embed-text:latest
2024-04-25 15:12:55 Creating Chroma vector store
2024-04-25 15:12:55 Initializing ParentDocumentRetriever with RedisDocstore
2024-04-25 15:12:55 Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
2024-04-25 15:12:55 Chat with Ollama, host: http://host.docker.internal:11434
2024-04-25 15:12:55 User query:  平凡的世界有几部分
2024-04-25 15:12:57 [nuxt] [request error] [unhandled] [500] ID undefined not found.
2024-04-25 15:12:57   at RedisDocstore.search (./.output/server/chunks/_/redis.mjs:59:13)  
2024-04-25 15:12:57   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
2024-04-25 15:12:57   at async Promise.all (index 0)  
2024-04-25 15:12:57   at async ParentDocumentRetriever._getRelevantDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:113:34)  
2024-04-25 15:12:57   at async ParentDocumentRetriever.getRelevantDocuments (./.output/server/node_modules/@langchain/core/dist/retrievers/index.js:67:29)  
2024-04-25 15:12:57   at async Object.handler (./.output/server/chunks/routes/api/models/index.post.mjs:73:27)  
2024-04-25 15:12:57   at async Object.handler (./.output/server/chunks/runtime.mjs:3125:19)  
2024-04-25 15:12:57   at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3391:7)

**Comment by jiansuer** [comment]
+1，我也遇到了 ，前台save按键的动画消失，终端显示chatollama-1  | Creating embeddings for Ollama served model: nomic-embed-text:latest
chatollama-1  | Creating Chroma vector store
chatollama-1  | Initializing ParentDocumentRetriever with RedisDocstore
chatollama-1  | Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
chatollama-1  | [nuxt] [request error] [unhandled] [500] fetch failed
chatollama-1  |   at node:internal/deps/undici/undici:12618:11  
chatollama-1  |   at async OllamaEmbeddings._request (./.output/server/node_modules/@langchain/community/dist/embeddings/ollama.js:107:26)  
chatollama-1  |   at async RetryOperation._fn (./.output/server/node_modules/p-retry/index.js:50:12)
