### ISSUE TITLE
添加知识库期间的问题

### ISSUE THREAD

**Issue by jiansuer** [sugarforever/chat-ollama#368]
问题1:docker显示只用了10%的cpu资源，能否进一步扩大，不然添加知识库的时候好慢好慢好慢。（m1pro）
问题2：添加知识库的过程中，终端有些warnning，蓝色的，报错，是说unknown type 1 chastring comand of 1，而且很多很多，在整个过程里都有。（我添加的是200来篇论文的pdf文件，有中文英语）
问题3：我在关机前进行了“docker compose down。开机后输入了docker compose up，但是重启后似乎还得重新装一遍，不知道为什么，是因为更新吗？

这个程序对我的帮助极大！感谢大佬！！

**Comment by jiansuer** [comment]
更新问题：添加失败，加入的是220份论文的pdf，有中文英文，embedding用的推荐的那个nomic
前台save按键的动画消失，终端显示chatollama-1 | Creating embeddings for Ollama served model: nomic-embed-text:latest
chatollama-1 | Creating Chroma vector store
chatollama-1 | Initializing ParentDocumentRetriever with RedisDocstore
chatollama-1 | Redis client options: { host: 'redis', port: 6379, username: undefined, password: undefined }
chatollama-1 | [nuxt] [request error] [unhandled] [500] fetch failed
chatollama-1 | at node:internal/deps/undici/undici:12618:11
chatollama-1 | at async OllamaEmbeddings._request (./.output/server/node_modules/@langchain/community/dist/embeddings/ollama.js:107:26)
chatollama-1 | at async RetryOperation._fn (./.output/server/node_modules/p-retry/index.js:50:12)

**Comment by jiansuer** [comment]
可能与一次性放入太多文件有关，一次10份pdf可以成功导入

**Comment by jiansuer** [comment]
或许可以加入某种分批向量化的选项，类似自动化脚本，每10份成功后再开始下一批10份文件的向量化
