### ISSUE TITLE
本地知识库添加PDF文件报错Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed

### ISSUE THREAD

**Issue by NewSNode** [sugarforever/chat-ollama#384]
运行环境：
ChatOllama使用docker compose安装并运行，Ollama使用docker运行。
在Setting中配置本地Ollama的Host：http://host.docker.internal:11434。

操作方法：
登录ChatOllama；
创建本地知识库，Embedding使用Ollama的nomic-embed-text（已下载）；
选择一个PDF文件，点击“save”按钮，查看ChatOllama后台日志，发现报错。

ChatOllama报错日志如下：
2024-04-28 12:21:01 URL: /api/auth/login User: null
2024-04-28 12:21:01 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-28 12:21:01 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-28 12:21:02 URL: /api/knowledgebases User: {"id":1,"name":"xxx(我的实际值)","email":"xxxx(我的实际值)","role":"user","scope":["test","user"],"iat":1714278061,"exp":1745814061}
2024-04-28 12:21:02 Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
2024-04-28 12:21:25 URL: /api/knowledgebases/5 User: {"id":1,"name":"xxxx(我的实际值)","email":"xxx(我的实际值)","role":"user","scope":["test","user"],"iat":1714278061,"exp":1745814061}
2024-04-28 12:21:25 Ollama:  {
2024-04-28 12:21:25   host: 'http://host.docker.internal:11434',
2024-04-28 12:21:25   username: null,
2024-04-28 12:21:25   password: null
2024-04-28 12:21:25 }
2024-04-28 12:21:26 Knowledge base ID:  5
2024-04-28 12:21:26 Ollama:  {
2024-04-28 12:21:26   host: 'http://host.docker.internal:11434',
2024-04-28 12:21:26   username: null,
2024-04-28 12:21:26   password: null
2024-04-28 12:21:26 }
2024-04-28 12:21:26 Authorization: bnVsbDpudWxs
2024-04-28 12:21:26 Update knowledge base 工业互联网 with ID 5
2024-04-28 12:21:27 Creating embeddings for Ollama served model: nomic-embed-text
2024-04-28 12:21:27 Creating Chroma vector store
2024-04-28 12:21:27 Initializing ParentDocumentRetriever with RedisDocstore
2024-04-28 12:21:27 Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
2024-04-28 12:22:32 Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed
2024-04-28 12:22:32     at Chroma.ensureCollection (file:///app/.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)
2024-04-28 12:22:32     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-28 12:22:32     at async Chroma.addVectors (file:///app/.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:126:28)
2024-04-28 12:22:32     at async ParentDocumentRetriever.addDocuments (file:///app/.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)
2024-04-28 12:22:32     at async ingestDocument (file:///app/.output/server/chunks/_/rag.mjs:297:3)
2024-04-28 12:22:32     at async Object.handler (file:///app/.output/server/chunks/routes/api/knowledgebases/_id_.put.mjs:60:7)
2024-04-28 12:22:32     at async Object.handler (file:///app/.output/server/chunks/runtime.mjs:3125:19)
2024-04-28 12:22:32     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3391:7)
2024-04-28 12:22:32 [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
2024-04-28 12:22:32   at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)  
2024-04-28 12:22:32   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
2024-04-28 12:22:32   at async Chroma.addVectors (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:126:28)  
2024-04-28 12:22:32   at async ParentDocumentRetriever.addDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)  
2024-04-28 12:22:32   at async ingestDocument (./.output/server/chunks/_/rag.mjs:297:3)  
2024-04-28 12:22:32   at async Object.handler (./.output/server/chunks/routes/api/knowledgebases/_id_.put.mjs:60:7)  
2024-04-28 12:22:32   at async Object.handler (./.output/server/chunks/runtime.mjs:3125:19)  
2024-04-28 12:22:32   at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3391:7)

各位大神，麻烦诊断下问题和解决方案，拜谢！！！
各位大神，麻烦诊断下问题和解决方案，拜谢！！！

其他信息补充：
1、使用Ollama下载到本地llama3模型可正常交互；
2、docker-compose.yaml文件内容（将Chromadb的端口改成了8300、ChatOllama镜像的端口改成了3300）:
version: '3.1'
services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8300:8000"
    restart: always
    volumes:
      - chromadb_data:/chroma/.chroma/index

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8300
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
      - REDIS_HOST=redis
    image: 0001coder/chatollama:latest
    ports:
      - "3300:3000"
    pull_policy: always
    restart: always
    volumes:
      - ~/.chatollama:/app/sqlite

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
  chromadb_data:
  redis_data:

**Comment by satrong** [comment]
duplicate #384
