### ISSUE TITLE
添加知识库报错

### ISSUE THREAD

**Issue by yw-2020** [sugarforever/chat-ollama#399]
KnowledgeBaseFile with ID:  16
2024-04-30 17:30:40 Creating embeddings for Ollama served model: nomic-embed-text:latest
2024-04-30 17:30:40 Creating Chroma vector store
2024-04-30 17:30:40 Initializing ParentDocumentRetriever with RedisDocstore
2024-04-30 17:30:40 Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
2024-04-30 17:30:40 0 URLs added to collection collection_18.
2024-04-30 17:30:40 All URL2024-04-30 17:30:40 Failed to verify extracted token: JsonWebTokenError: jwt must be provideds: Set(0) {}
**2024-04-30 17:30:40 Failed to verify extracted token: JsonWebTokenError: jwt must be provided**
2024-04-30 17:30:40     at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-30 17:30:40     at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6954:18)
2024-04-30 17:30:40     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6965:16)
2024-04-30 17:30:40     at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3126:31)
2024-04-30 17:30:40     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-30 17:30:40     at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3392:7)

**Comment by sugarforever** [comment]
```2024-04-30 17:30:40 Failed to verify extracted token: JsonWebTokenError: jwt must be provided
2024-04-30 17:30:40 at module.exports [as verify] (/app/.output/server/node_modules/jsonwebtoken/verify.js:60:17)
2024-04-30 17:30:40 at verifyToken (file:///app/.output/server/chunks/runtime.mjs:6954:18)
2024-04-30 17:30:40 at Object.handler (file:///app/.output/server/chunks/runtime.mjs:6965:16)
2024-04-30 17:30:40 at Object.handler (file:///app/.output/server/chunks/runtime.mjs:3126:31)
2024-04-30 17:30:40 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-30 17:30:40 at async Server.toNodeHandle (file:///app/.output/server/chunks/runtime.mjs:3392:7)```

抱歉。这并不是一个知识库创建中的错误。这个 `JsonWebTokenError` 是因为你没有登录，而操作中会解析当前用户，没有有效token，因此打印了该信息。

可以忽略。我会尽快调整这个信息输出形式。
