### ISSUE TITLE
创建知识库不成功，求助？

### ISSUE THREAD

**Issue by fxjs** [sugarforever/chat-ollama#401]
点了 save， 在网页抓取一会之后，右上角弹窗报这个错：

Cannot read properties of undefined (reading '0')

` ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '0')
  at OpenAIEmbeddings.embedDocuments (./node_modules/.pnpm/@langchain+openai@0.0.15/node_modules/@langchain/openai/dist/embeddings.js:189:46)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Chroma.addDocuments (./node_modules/.pnpm/@langchain+community@0.0.33_@zilliz+milvus2-sdk-node@2.3.5_chromadb@1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e/node_modules/@langchain/community/dist/vectorstores/chroma.js:79:32)  
  at ingestURLs (./server/utils/rag.ts:112:1)  
  at Object.handler (./server/api/knowledgebases/index.post.ts:66:1)  
  at async ./node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1962:19  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2249:7)
`

是啥原因呢？

**Comment by sugarforever** [comment]
请帮忙确认一下几点：
1. 是否配置了有效的OpenAI API Key
2. Chroma是否有正常运行？

从错误信息看，像是OpenAI 的 embed API调用出现的问题。

**Comment by fxjs** [comment]
> 请帮忙确认一下几点：
> 
> 1. 是否配置了有效的OpenAI API Key
> 2. Chroma是否有正常运行？
> 
> 从错误信息看，像是OpenAI 的 embed API调用出现的问题。

---

1、我用的是官转的Endpoint （api。oaipro。com），用key调gpt4是可以的，看说明里是支持所有模型的；
2、localhost:8000 输出的是 {"detail":"Not Found"}。

感谢大佬指点。
