### ISSUE TITLE
访问知识库出错

### ISSUE THREAD

**Issue by gzlimingguo** [sugarforever/chat-ollama#436]
环境：MacBook Pro M3，基于docker

能够正常创建知识库，但是进行对话时，后台报错：
chromadb-1    | ERROR:    [09-05-2024 06:48:37] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_3

**Comment by gzlimingguo** [comment]
错误
Chroma getOrCreateCollection error: Error: ValueError('Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_3 ') 如果启用了代理，请确保代理正常工作。

**Comment by hzluyang** [comment]
我也是一样的问题

**Comment by tanzhixu** [comment]
一样的问题

**Comment by hzluyang** [comment]
我研究了一下 报错应该是 Chroma 对于collection的命名要求：getOrCreateCollection error: Error: ValueError('Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address,

这边代码里面创建的集合是collection_1  collection_2 不符合“starts and ends with an alphanumeric character”

这个代码里面是不是改一下默认集合创建的部分？
我自己打算绕过去 
a 降级Chroma版本 不知道是不是高版本带来的命名限制
b 干脆不用Chroma用milvus

各位有绕过去的给个留言

**Comment by hzluyang** [comment]
chromadb_1    |   File "/chroma/chromadb/api/segment.py", line 163, in create_collection
chromadb_1    |     check_index_name(name)
chromadb_1    |   File "/chroma/chromadb/api/segment.py", line 79, in check_index_name
chromadb_1    |     raise ValueError(msg)
chromadb_1    | ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_2 
chatollama_1  | [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: ValueError('Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_2 ')

**Comment by cylcc06** [comment]
2024-05-09 20:20:57 Starting 'uvicorn chromadb.app:app' with args: --workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30
2024-05-09 20:21:04 WARNING:  [09-05-2024 12:21:04] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048576. chroma_server_nofile will not be set.
2024-05-09 20:21:05 INFO:     [09-05-2024 12:21:05] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component System
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component OpenTelemetryClient
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component SqliteDB
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component QuotaEnforcer
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component Posthog
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component LocalSegmentManager
2024-05-09 20:21:05 DEBUG:    [09-05-2024 12:21:05] Starting component SegmentAPI
2024-05-09 20:21:06 INFO:     [09-05-2024 12:21:06] Started server process [1]
2024-05-09 20:21:06 INFO:     [09-05-2024 12:21:06] Waiting for application startup.
2024-05-09 20:21:06 INFO:     [09-05-2024 12:21:06] Application startup complete.
2024-05-09 20:21:06 INFO:     [09-05-2024 12:21:06] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-05-09 20:21:16 INFO:     [09-05-2024 12:21:16] 192.168.65.1:19569 - "GET / HTTP/1.1" 404
2024-05-09 20:21:35 ERROR:    [09-05-2024 12:21:35] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_4 
2024-05-09 20:21:35 Traceback (most recent call last):
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 97, in receive
2024-05-09 20:21:35     return self.receive_nowait()
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
2024-05-09 20:21:35     raise WouldBlock
2024-05-09 20:21:35 anyio.WouldBlock
2024-05-09 20:21:35 
2024-05-09 20:21:35 During handling of the above exception, another exception occurred:
2024-05-09 20:21:35 
2024-05-09 20:21:35 Traceback (most recent call last):
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 159, in call_next
2024-05-09 20:21:35     message = await recv_stream.receive()
2024-05-09 20:21:35               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 112, in receive
2024-05-09 20:21:35     raise EndOfStream
2024-05-09 20:21:35 anyio.EndOfStream
2024-05-09 20:21:35 
2024-05-09 20:21:35 During handling of the above exception, another exception occurred:
2024-05-09 20:21:35 
2024-05-09 20:21:35 Traceback (most recent call last):
2024-05-09 20:21:35   File "/chroma/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
2024-05-09 20:21:35     return await call_next(request)
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-05-09 20:21:35     raise app_exc
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-05-09 20:21:35     await self.app(scope, receive_or_disconnect, send_no_error)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-05-09 20:21:35     with collapse_excgroups():
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
2024-05-09 20:21:35     self.gen.throw(typ, value, traceback)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-05-09 20:21:35     raise exc
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-05-09 20:21:35     response = await self.dispatch_func(request, call_next)
2024-05-09 20:21:35                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/chroma/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
2024-05-09 20:21:35     return await call_next(request)
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-05-09 20:21:35     raise app_exc
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-05-09 20:21:35     await self.app(scope, receive_or_disconnect, send_no_error)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-09 20:21:35     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-09 20:21:35     raise exc
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-09 20:21:35     await app(scope, receive, sender)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-05-09 20:21:35     await self.middleware_stack(scope, receive, send)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-05-09 20:21:35     await route.handle(scope, receive, send)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-05-09 20:21:35     await self.app(scope, receive, send)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-05-09 20:21:35     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-09 20:21:35     raise exc
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-09 20:21:35     await app(scope, receive, sender)
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-05-09 20:21:35     response = await func(request)
2024-05-09 20:21:35                ^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-05-09 20:21:35     raw_response = await run_endpoint_function(
2024-05-09 20:21:35                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-05-09 20:21:35     return await dependant.call(**values)
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/chroma/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
2024-05-09 20:21:35     return await f(*args, **kwargs)
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/chroma/chromadb/server/fastapi/__init__.py", line 630, in create_collection
2024-05-09 20:21:35     await to_thread.run_sync(
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-05-09 20:21:35     return await get_async_backend().run_sync_in_worker_thread(
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
2024-05-09 20:21:35     return await future
2024-05-09 20:21:35            ^^^^^^^^^^^^
2024-05-09 20:21:35   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-05-09 20:21:35     result = context.run(func, *args)
2024-05-09 20:21:35              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/chroma/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
2024-05-09 20:21:35     return self._api.create_collection(
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/chroma/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
2024-05-09 20:21:35     return f(*args, **kwargs)
2024-05-09 20:21:35            ^^^^^^^^^^^^^^^^^^
2024-05-09 20:21:35   File "/chroma/chromadb/api/segment.py", line 169, in create_collection
2024-05-09 20:21:35     check_index_name(name)
2024-05-09 20:21:35   File "/chroma/chromadb/api/segment.py", line 81, in check_index_name
2024-05-09 20:21:35     raise ValueError(msg)

**Comment by tanzhixu** [comment]
找到问题了，index_name 多个一个空格

**Comment by gzlimingguo** [comment]
> 找到问题了，index_name 多个一个空格

您的意思是？代码中有错？那要怎么弄呢？

**Comment by gzlimingguo** [comment]
在docker环境下，如果想改为使用milvus，按照如下编辑.env文件后，是将这个文件放在哪里呢？放在ChatOllama-Docker目录，还是用户根目录呢？

Please refer to the .env.example for how to work with your vector database setup.

# Supported values: chroma, milvus
VECTOR_STORE=chroma
CHROMADB_URL=http://localhost:8000
MILVUS_URL=http://localhost:19530
By default ChatOllama is using Chroma. If you'd like to use Milvus, set VECTOR_STORE to milvus and specify the corresponding URL. It works both in the development server and Docker containers.

**Comment by cylcc06** [comment]
> 在docker环境下，如果想改为使用milvus，按照如下编辑.env文件后，是将这个文件放在哪里呢？放在ChatOllama-Docker目录，还是用户根目录呢？
> 
> Please refer to the .env.example for how to work with your vector database setup.
> 
> # Supported values: chroma, milvus
> VECTOR_STORE=chroma CHROMADB_URL=http://localhost:8000 MILVUS_URL=http://localhost:19530 By default ChatOllama is using Chroma. If you'd like to use Milvus, set VECTOR_STORE to milvus and specify the corresponding URL. It works both in the development server and Docker containers.

放在原来的位置。

**Comment by hzluyang** [comment]
> 找到问题了，index_name 多个一个空格

我猜的也是 这个怎么调整代码

**Comment by dsxksss** [comment]
我也遇到了这个问题，对话是没问题但使用文档对话就出现了

**Comment by cylcc06** [comment]
> > 在docker环境下，如果想改为使用milvus，按照如下编辑.env文件后，是将这个文件放在哪里呢？放在ChatOllama-Docker目录，还是用户根目录呢？
> > Please refer to the .env.example for how to work with your vector database setup.
> > # Supported values: chroma, milvus
> > VECTOR_STORE=chroma CHROMADB_URL=http://localhost:8000 MILVUS_URL=http://localhost:19530 By default ChatOllama is using Chroma. If you'd like to use Milvus, set VECTOR_STORE to milvus and specify the corresponding URL. It works both in the development server and Docker containers.
> 
> 放在原来的位置。

感觉是进入docker里面，然后找到.env。 修改配置内容，然后重启docker环境。

**Comment by gzlimingguo** [comment]
> > > 在docker环境下，如果想改为使用milvus，按照如下编辑.env文件后，是将这个文件放在哪里呢？放在ChatOllama-Docker目录，还是用户根目录呢？
> > > Please refer to the .env.example for how to work with your vector database setup.
> > > # Supported values: chroma, milvus
> > > VECTOR_STORE=chroma CHROMADB_URL=http://localhost:8000 MILVUS_URL=http://localhost:19530 By default ChatOllama is using Chroma. If you'd like to use Milvus, set VECTOR_STORE to milvus and specify the corresponding URL. It works both in the development server and Docker containers.
> > 
> > 
> > 放在原来的位置。
> 
> 感觉是进入docker里面，然后找到.env。 修改配置内容，然后重启docker环境。

进入docker里面找.env吗？这个要怎么找？

**Comment by tanzhixu** [comment]
> > 找到问题了，index_name 多个一个空格
> 
> 我猜的也是 这个怎么调整代码



> > 找到问题了，index_name 多个一个空格
> 
> 您的意思是？代码中有错？那要怎么弄呢？

我在chroma源码里改的，

def check_index_name(index_name: str) -> None:
msg = (
"Expected collection name that "
"(1) contains 3-63 characters, "
"(2) starts and ends with an alphanumeric character, "
"(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), "
"(4) contains no two consecutive periods (..) and "
"(5) is not a valid IPv4 address, "
f"got {index_name}"
)
index_name = index_name.strip()  # 加了这行
if len(index_name) < 3 or len(index_name) > 63:
raise ValueError(msg)
if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name):
raise ValueError(msg)
if ".." in index_name:
raise ValueError(msg)
if re.match("^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$", index_name):
raise ValueError(msg)

**Comment by hzluyang** [comment]
> > > 找到问题了，index_name 多个一个空格
> > 
> > 
> > 我猜的也是 这个怎么调整代码
> 
> > > 找到问题了，index_name 多个一个空格
> > 
> > 
> > 您的意思是？代码中有错？那要怎么弄呢？
> 
> 我在chroma源码里改的，
> 
> def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)

哥这招绝了  我还在找chatollama里面哪一个ts文件多带了个空格 我也改一把 有效吗

**Comment by dsxksss** [comment]
> > > > 找到问题了，index_name 多个一个空格
> > > 
> > > 
> > > 我猜的也是 这个怎么调整代码
> > 
> > 
> > > > 找到问题了，index_name 多个一个空格
> > > 
> > > 
> > > 您的意思是？代码中有错？那要怎么弄呢？
> > 
> > 
> > 我在chroma源码里改的，
> > def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)
> 
> 哥这招绝了 我还在找chatollama里面哪一个ts文件多带了个空格 我也改一把 有效吗

所以chatollama对这一部分实现并没有问题吗?🤔

**Comment by tanzhixu** [comment]
> > > > 找到问题了，index_name 多个一个空格
> > > 
> > > 
> > > 我猜的也是 这个怎么调整代码
> > 
> > 
> > > > 找到问题了，index_name 多个一个空格
> > > 
> > > 
> > > 您的意思是？代码中有错？那要怎么弄呢？
> > 
> > 
> > 我在chroma源码里改的，
> > def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)
> 
> 哥这招绝了 我还在找chatollama里面哪一个ts文件多带了个空格 我也改一把 有效吗

改完后，我这没问题，能正常运行。

**Comment by gzlimingguo** [comment]
> > > 找到问题了，index_name 多个一个空格
> > 
> > 
> > 我猜的也是 这个怎么调整代码
> 
> > > 找到问题了，index_name 多个一个空格
> > 
> > 
> > 您的意思是？代码中有错？那要怎么弄呢？
> 
> 我在chroma源码里改的，
> 
> def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)

太棒了！ 但是最好还是看能否让01coder老师在chatollama中来完善一下，并更新一下docker image。

**Comment by hzluyang** [comment]
> > > > > 找到问题了，index_name 多个一个空格
> > > > 
> > > > 
> > > > 我猜的也是 这个怎么调整代码
> > > 
> > > 
> > > > > 找到问题了，index_name 多个一个空格
> > > > 
> > > > 
> > > > 您的意思是？代码中有错？那要怎么弄呢？
> > > 
> > > 
> > > 我在chroma源码里改的，
> > > def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)
> > 
> > 
> > 哥这招绝了 我还在找chatollama里面哪一个ts文件多带了个空格 我也改一把 有效吗
> 
> 改完后，我这没问题，能正常运行。

@tanzhixu 我改完了可以运行但是 基于知识库的问答基本上都未能命中 不知道你这边的知识库文档是否符合预期

**Comment by tanzhixu** [comment]
> > > > > > 找到问题了，index_name 多个一个空格
> > > > > 
> > > > > 
> > > > > 我猜的也是 这个怎么调整代码
> > > > 
> > > > 
> > > > > > 找到问题了，index_name 多个一个空格
> > > > > 
> > > > > 
> > > > > 您的意思是？代码中有错？那要怎么弄呢？
> > > > 
> > > > 
> > > > 我在chroma源码里改的，
> > > > def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)
> > > 
> > > 
> > > 哥这招绝了 我还在找chatollama里面哪一个ts文件多带了个空格 我也改一把 有效吗
> > 
> > 
> > 改完后，我这没问题，能正常运行。
> 
> @tanzhixu 我改完了可以运行但是 基于知识库的问答基本上都未能命中 不知道你这边的知识库文档是否符合预期

不太行，有时间就卡那了。

**Comment by cylcc06** [comment]
> > > 找到问题了，index_name 多个一个空格
> > 
> > 
> > 我猜的也是 这个怎么调整代码
> 
> > > 找到问题了，index_name 多个一个空格
> > 
> > 
> > 您的意思是？代码中有错？那要怎么弄呢？
> 
> 我在chroma源码里改的，
> 
> def check_index_name(index_name: str) -> None: msg = ( "Expected collection name that " "(1) contains 3-63 characters, " "(2) starts and ends with an alphanumeric character, " "(3) otherwise contains only alphanumeric characters, underscores or hyphens (-), " "(4) contains no two consecutive periods (..) and " "(5) is not a valid IPv4 address, " f"got {index_name}" ) index_name = index_name.strip() # 加了这行 if len(index_name) < 3 or len(index_name) > 63: raise ValueError(msg) if not re.match("^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]$", index_name): raise ValueError(msg) if ".." in index_name: raise ValueError(msg) if re.match("^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", index_name): raise ValueError(msg)


没有报错，但是Collection collection_21 is not created.
2024-05-10 13:43:00 INFO:     [10-05-2024 05:43:00] 192.168.65.1:37007 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
2024-05-10 13:54:04 INFO:     [10-05-2024 05:54:04] 192.168.65.1:37008 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
2024-05-10 13:56:01 DEBUG:    [10-05-2024 05:56:01] Starting component PersistentLocalHnswSegment
2024-05-10 13:56:02 INFO:     [10-05-2024 05:56:02] 192.168.65.1:37009 - "POST /api/v1/collections/3f54c6a6-e643-4ec0-8beb-92d6e6c13c48/upsert HTTP/1.1" 200
2024-05-10 13:56:02 INFO:     [10-05-2024 05:56:02] Collection collection_21 is not created.
2024-05-10 13:56:02 INFO:     [10-05-2024 05:56:02] 192.168.65.1:37009 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
2024-05-10 13:56:27 INFO:     [10-05-2024 05:56:27] 192.168.65.1:37010 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
2024-05-10 13:56:27 DEBUG:    [10-05-2024 05:56:27] Starting component PersistentLocalHnswSegment
2024-05-10 13:56:27 INFO:     [10-05-2024 05:56:27] 192.168.65.1:37010 - "POST /api/v1/collections/14ff52bf-dc7a-4eef-92fc-512ed25424b5/query HTTP/1.1" 200

**Comment by satrong** [comment]
感谢大家的反馈，经排查确实是 collection name 格式错误，名字后面多了一个空格导致的。目前已修复，请大家使用最新代码使用
