### ISSUE TITLE
错误 fetch failed 如果启用了代理，请确保代理正常工作。知识库添加正常，对话时响应失败

### ISSUE THREAD

**Issue by cylcc06** [sugarforever/chat-ollama#442]
嵌入模型：nomic-embed-text:latest
对话模型：llama/llama3:latest

URL: /api/models/chat User: null
Chat with knowledge base with id:  23
Knowledge base aaa with embedding "nomic-embed-text:latest"
Creating embeddings for Ollama served model: nomic-embed-text:latest
Creating Chroma vector store
Initializing vector store retriever
Chat with Ollama, host: http://127.0.0.1:11434
User query:  白鲸里面的船长是谁
Relevant documents:  [ Document {
    pageContent:
     '1．海与鲸的诱惑\r\n\r\n\n\t很多年以前，那时我的钱包瘪瘪的，陆地上看来没什么好混得了，干脆下海吧，去在我们这个世界上占
......
漉的，很沉。\r\n\n\r\n\n\t　　很难想像，那个标枪手穿上这样一件奇怪的衣服招摇过市！\r\n\n\r\n\n\t　　我迫不及待地往下脱这毯子，情急之中扭了一下头，酸疼酸疼的'... 76512 more characters,
    metadata: { blobType: 'text/plain', source: '《白鲸》赫尔曼·麦尔维尔 2.txt' } } ]

 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11731:11)  
  at async createOllamaStream (./node_modules/.pnpm/@langchain+community@0.0.33_@zilliz+milvus2-sdk-node@2.3.5_chromadb@1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e/node_modules/@langchain/community/dist/utils/ollama.js:9:22)  
  at async createOllamaChatStream (./node_modules/.pnpm/@langchain+community@0.0.33_@zilliz+milvus2-sdk-node@2.3.5_chromadb@1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e/node_modules/@langchain/community/dist/utils/ollama.js:57:5)  
  at async ChatOllama._streamResponseChunks (./node_modules/.pnpm/@langchain+community@0.0.33_@zilliz+milvus2-sdk-node@2.3.5_chromadb@1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e/node_modules/@langchain/community/dist/chat_models/ollama.js:396:30)  
  at async ChatOllama._streamIterator (./node_modules/.pnpm/@langchain+core@0.1.54/node_modules/@langchain/core/dist/language_models/chat_models.js:78:34)  
  at async ChatOllama.transform (./node_modules/.pnpm/@langchain+core@0.1.54/node_modules/@langchain/core/dist/runnables/base.js:375:9)  
  at async RunnableSequence._streamIterator (./node_modules/.pnpm/@langchain+core@0.1.54/node_modules/@langchain/core/dist/runnables/base.js:1116:30)

**Comment by cylcc06** [comment]
补充：
添加知识库时候，chroma日志如下：
2024-05-11 00:04:08 INFO:     [10-05-2024 16:04:08] 192.168.65.1:42476 - "POST /api/v1/collections/3d890992-f4db-4c35-aa1d-1896682cbdc1/query HTTP/1.1" 200
2024-05-11 00:09:40 INFO:     [10-05-2024 16:09:40] Collection collection_24 is not created.
2024-05-11 00:09:40 INFO:     [10-05-2024 16:09:40] 192.168.65.1:42477 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
2024-05-11 00:09:43 WARNING:  [10-05-2024 16:09:43] Number of requested results 4 is greater than number of elements in index 1, updating n_results = 1
2024-05-11 00:09:43 INFO:     [10-05-2024 16:09:43] 192.168.65.1:42477 - "POST /api/v1/collections/3d890992-f4db-4c35-aa1d-1896682cbdc1/query HTTP/1.1" 200

**Comment by cylcc06** [comment]
> 嵌入模型：nomic-embed-text:latest 对话模型：llama/llama3:latest
> 
> URL: /api/models/chat User: null Chat with knowledge base with id: 23 Knowledge base aaa with embedding "nomic-embed-text:latest" Creating embeddings for Ollama served model: nomic-embed-text:latest Creating Chroma vector store Initializing vector store retriever Chat with Ollama, host: http://127.0.0.1:11434 User query: 白鲸里面的船长是谁 Relevant documents: [ Document { pageContent: '1．海与鲸的诱惑\r\n\r\n\n\t很多年以前，那时我的钱包瘪瘪的，陆地上看来没什么好混得了，干脆下海吧，去在我们这个世界上占 ...... 漉的，很沉。\r\n\n\r\n\n\t　　很难想像，那个标枪手穿上这样一件奇怪的衣服招摇过市！\r\n\n\r\n\n\t　　我迫不及待地往下脱这毯子，情急之中扭了一下头，酸疼酸疼的'... 76512 more characters, metadata: { blobType: 'text/plain', source: '《白鲸》赫尔曼·麦尔维尔 2.txt' } } ]
> 
> ERROR [nuxt] [request error] [unhandled] [500] fetch failed at Object.fetch (node:internal/deps/undici/undici:11731:11) at async createOllamaStream (./node_modules/.pnpm/@langchain+community@[0.0.33_@zilliz](mailto:0.0.33_@zilliz)+milvus2-sdk-node@2.3.5_chromadb@[1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e](mailto:1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e)/node_modules/@langchain/community/dist/utils/ollama.js:9:22) at async createOllamaChatStream (./node_modules/.pnpm/@langchain+community@[0.0.33_@zilliz](mailto:0.0.33_@zilliz)+milvus2-sdk-node@2.3.5_chromadb@[1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e](mailto:1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e)/node_modules/@langchain/community/dist/utils/ollama.js:57:5) at async ChatOllama._streamResponseChunks (./node_modules/.pnpm/@langchain+community@0.0.33_@zilliz+milvus2-sdk-node@2.3.5_chromadb@[1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e](mailto:1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e)/node_modules/@langchain/community/dist/chat_models/ollama.js:396:30) at async ChatOllama._streamIterator (./node_modules/.pnpm/@langchain+core@0.1.54/node_modules/@langchain/core/dist/language_models/chat_models.js:78:34) at async ChatOllama.transform (./node_modules/.pnpm/@langchain+core@0.1.54/node_modules/@langchain/core/dist/runnables/base.js:375:9) at async RunnableSequence._streamIterator (./node_modules/.pnpm/@langchain+core@0.1.54/node_modules/@langchain/core/dist/runnables/base.js:1116:30)

更换成这个模型，有响应，难道电脑太差，跑步起来7b的吗？
gemma/gemma:2b
