### ISSUE TITLE
Chroma getOrCreateCollection error: Error: TypeError: fetch failed

### ISSUE THREAD

**Issue by jingnorth** [sugarforever/chat-ollama#446]
远程服务器上用docker方式安装了chatollama ，当创建知识库时出现报错Chroma getOrCreateCollection error: Error: TypeError: fetch failed，请问是否是上传文件失败？需要打开什么访问端口吗，因为服务器安全策略比较严格，目前远程不带知识库问答正常

**Comment by jingnorth** [comment]
报错是
Invalid token from Authorization header.
URL: /api/knowledgebases User: null
Ollama:  {
  host: 'http://10.75.44.181:11434',
  username: 'aaaa',
  password: 'bbbb'
}
Authorization: c3Vubm9ydGg6MXFhejFxYXo=
Current User:  null
Created knowledge base inv_short_txt: 2 by anonymous
Creating embeddings for Ollama served model: nomic-embed-text:latest
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
[nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
  at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Chroma.addVectors (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:126:28)  
  at async ParentDocumentRetriever.addDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)  
  at async ingestDocument (./.output/server/chunks/_/rag.mjs:293:3)  
  at async Object.handler (./.output/server/chunks/routes/api/index.post2.mjs:85:5)  
  at async Object.handler (./.output/server/chunks/runtime.mjs:3126:19)  
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3392:7)

**Comment by jingnorth** [comment]
报错是
Invalid token from Authorization header.
URL: /api/knowledgebases User: null
Ollama: {
host: 'http://11.115.22.11:11434/',
username: 'aaaa',
password: 'bbbb'
}
Authorization: c3Vubm9ydGg6MXFhejFxYXo=
Current User: null
Created knowledge base inv_short_txt: 2 by anonymous
Creating embeddings for Ollama served model: nomic-embed-text:latest
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options: { host: 'redis', port: 6379, username: undefined, password: undefined }
[nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Chroma.addVectors (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:126:28)
at async ParentDocumentRetriever.addDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:167:13)
at async ingestDocument (./.output/server/chunks/_/rag.mjs:293:3)
at async Object.handler (./.output/server/chunks/routes/api/index.post2.mjs:85:5)
at async Object.handler (./.output/server/chunks/runtime.mjs:3126:19)
at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3392:7)

**Comment by jingnorth** [comment]
请帮忙看下

**Comment by jingnorth** [comment]
还得自己来。。发现yaml文件里的9000端口设置并不生效，改回默认的8000才可以，不知道是不是bug
image: chromadb/chroma
ports:
- "9000:9000"
restart: always
volumes:
- chromadb_data:/chroma/.chroma/index

chatollama:
environment:
- CHROMADB_URL=http://chromadb:9000/

**Comment by satrong** [comment]
👍

这种问题基本上就是程序未能正常连上 chromadb 导致的
