### ISSUE TITLE
知识库问答报错

### ISSUE THREAD

**Issue by cjcqqqq** [sugarforever/chat-ollama#461]
有些知识库能够正常问答，当知识库文档较多时出现如下报错。
知识库问答前端界面报错如下：
ID 4d079db0-40ec-4258-88f5-df94e6a3cc13 not found. 如果启用了代理，请确保代理正常工作。
![chatollama](https://github.com/sugarforever/chat-ollama/assets/15957240/2eb81c9d-2e19-47d6-aed6-adaebaa7f4e6)
后台服务报错如下：
2024-05-17 15:36:30 Invalid token from Authorization header.
2024-05-17 15:36:30 URL: /api/models/chat User: null
2024-05-17 15:36:30 Chat with knowledge base with id:  33
2024-05-17 15:36:30 Knowledge base 行业报告和三方方案 with embedding "nomic-embed-text:latest"
2024-05-17 15:36:30 Creating embeddings for Ollama served model: nomic-embed-text:latest
2024-05-17 15:36:30 Creating Chroma vector store
2024-05-17 15:36:30 Initializing ParentDocumentRetriever with RedisDocstore
2024-05-17 15:36:30 Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
2024-05-17 15:36:30 Chat with Ollama, host: http://host.docker.internal:11434
2024-05-17 15:36:30 User query:  华为对智能网联发展趋势的洞察分析
2024-05-17 15:36:30 [nuxt] [request error] [unhandled] [500] ID 4d079db0-40ec-4258-88f5-df94e6a3cc13 not found.
2024-05-17 15:36:30   at RedisDocstore.search (./.output/server/chunks/_/redis.mjs:59:13)  
2024-05-17 15:36:30   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
2024-05-17 15:36:30   at async Promise.all (index 0)  
2024-05-17 15:36:30   at async ParentDocumentRetriever._getRelevantDocuments (./.output/server/node_modules/langchain/dist/retrievers/parent_document.js:113:34)  
2024-05-17 15:36:30   at async ParentDocumentRetriever.getRelevantDocuments (./.output/server/node_modules/@langchain/core/dist/retrievers/index.js:67:29)  
2024-05-17 15:36:30   at async Object.handler (./.output/server/chunks/routes/api/models/index.post.mjs:172:27)  
2024-05-17 15:36:30   at async Object.handler (./.output/server/chunks/runtime.mjs:3126:19)  
2024-05-17 15:36:30   at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3392:7)

**Comment by FlickerMi** [comment]
俺也一样
