### ISSUE TITLE
使用本地知识库报错 request to http://peanutshell:8000/v1/rerank failed, reason: getaddrinfo ENOTFOUND peanutshell

### ISSUE THREAD

**Issue by zorrol** [sugarforever/chat-ollama#476]
错误日志如下：
2024-05-23 14:04:22 Chat with Ollama, host: http://host.docker.internal:11434
2024-05-23 14:04:22 User query:  6G的使用场景有哪些？
2024-05-23 14:04:23 Relevant documents:  []
2024-05-23 14:04:23 Cohere Rerank Options:  {
2024-05-23 14:04:23   apiKey: 'xxxxx',
2024-05-23 14:04:23   baseUrl: 'http://peanutshell:8000/v1',
2024-05-23 14:04:23   model: 'ms-marco-MiniLM-L-6-v2',
2024-05-23 14:04:23   topN: 4
2024-05-23 14:04:23 }
2024-05-23 14:04:23 [nuxt] [request error] [unhandled] [500] request to http://peanutshell:8000/v1/rerank failed, reason: getaddrinfo ENOTFOUND peanutshell
2024-05-23 14:04:23   at CohereClient.<anonymous> (./.output/server/node_modules/cohere-ai/Client.js:488:27)  
2024-05-23 14:04:23   at Generator.next (<anonymous>)  
2024-05-23 14:04:23   at fulfilled (./.output/server/node_modules/cohere-ai/Client.js:31:58)  
2024-05-23 14:04:23   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

我看日志是花生壳的错误，运行本地知识库，是还需要装花生壳吗？

**Comment by zorrol** [comment]
需要Docker 中启动peanutshell，启动后就解决了。

**Comment by ShuaiZePing** [comment]
> 需要Docker 中启动peanutshell，启动后就解决了。

请问在哪个docker容器中启用呀？
