### ISSUE TITLE
创建知识库上传文件报错

### ISSUE THREAD

**Issue by 2twentyto2** [sugarforever/chat-ollama#564]
ERROR  [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
  at Chroma.ensureCollection (/E:/gitINe/chat-ollama/node_modules/.pnpm/@langchain+community@0.0.33_@zilliz+milvus2-sdk-node@2.3.5_chromadb@1.8.1_html-to-text@9.0.5__agb6zier7q7j3juxcraj2tnm3e/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)
  at createRetriever (E:\gitINe\chat-ollama\server\retriever\index.ts:11:5)
  at ingestDocument (E:\gitINe\chat-ollama\server\utils\rag.ts:84:1)
  at Object.handler (E:\gitINe\chat-ollama\server\api\knowledgebases\index.post.ts:56:1)
  at async /E:/gitINe/chat-ollama/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (/E:/gitINe/chat-ollama/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/E:/gitINe/chat-ollama/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2249:7)

**Comment by 2twentyto2** [comment]
Chroma在docker部署运行，chatollama和ollma都在本地部署运行

**Comment by h3clikejava** [comment]
I have same problem...
