### ISSUE TITLE
Cannot read properties of undefined (reading 'find) when tried to chat with a created kB.

### ISSUE THREAD

**Issue by wukong919** [sugarforever/chat-ollama#575]
Logs: 
Creating embeddings for Ollama served model: nomic-embed-text:latest
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
19 URLs added to collection collection_17.
All URLs: Set(19) {
  'https://vmc.techzone.vmware.com/resource/vmware-cloud-aws-network-architecture',
  'https://vmc.techzone.vmware.com',
  'https://vmc.techzone.vmware.com/vmware-cloud-well-architected#framework',
  'https://vmc.techzone.vmware.com/vmware-cloud-well-architected',
  'https://vmc.techzone.vmware.com/vmware-cloud-well-architected#designs',
  'https://vmc.techzone.vmware.com/alibaba-cloud-vmware-service',
  'https://vmc.techzone.vmware.com/azure-vmware-solution',
  'https://vmc.techzone.vmware.com/google-cloud-vmware-engine',
  'https://vmc.techzone.vmware.com/oracle-cloud-vmware-solution',
  'https://vmc.techzone.vmware.com/vmware-cloud-aws',
  'https://vmc.techzone.vmware.com/vmware-cloud-aws-outposts',
  'https://vmc.techzone.vmware.com/multi-cloud',
  'https://vmc.techzone.vmware.com/vmware-sovereign-cloud',
  'https://vmc.techzone.vmware.com/app-modernization',
  'https://vmc.techzone.vmware.com/migration',
  'https://vmc.techzone.vmware.com/cloud-vdi',
  'https://vmc.techzone.vmware.com/data-center-extension',
  'https://vmc.techzone.vmware.com/disaster-recovery',
  'https://vmc.techzone.vmware.com/blog'
}
Knowledge base file created with ID:  15
Knowledge base file created with ID:  16
Knowledge base file created with ID:  17
Knowledge base file created with ID:  18
Knowledge base file created with ID:  19
Knowledge base file created with ID:  20
Knowledge base file created with ID:  21
Knowledge base file created with ID:  22
Knowledge base file created with ID:  23
Knowledge base file created with ID:  24
Knowledge base file created with ID:  25
Knowledge base file created with ID:  26
Knowledge base file created with ID:  27
Knowledge base file created with ID:  28
Knowledge base file created with ID:  29
Knowledge base file created with ID:  30
Knowledge base file created with ID:  31
Knowledge base file created with ID:  32
Knowledge base file created with ID:  33
URL: /api/knowledgebases User: {"id":2,"name":"wukong919","email":"wukong919@hotmail.com","role":"user","scope":["test","user"],"iat":1726710901,"exp":1758246901}
URL: /api/instruction User: {"id":2,"name":"wukong919","email":"wukong919@hotmail.com","role":"user","scope":["test","user"],"iat":1726710901,"exp":1758246901}
URL: /api/knowledgebases User: {"id":2,"name":"wukong919","email":"wukong919@hotmail.com","role":"user","scope":["test","user"],"iat":1726710901,"exp":1758246901}
URL: /api/models/chat User: null
Chat with knowledge base with id:  17
Knowledge base test1000 with embedding "nomic-embed-text:latest"
Creating embeddings for Ollama served model: nomic-embed-text:latest
Creating Chroma vector store
Initializing ParentDocumentRetriever with RedisDocstore
Redis client options:  { host: 'redis', port: 6379, username: undefined, password: undefined }
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'find')
  at createChatModel (./.output/server/chunks/_/index2.mjs:453:35)  
  at Object.handler (./.output/server/chunks/routes/api/models/index.post.mjs:182:18)  
  at async Object.handler (./.output/server/chunks/runtime.mjs:3126:19)  
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3392:7)

Any clue of what did cause the issue?

**Comment by wukong919** [comment]
cant reproduce the issue any more.
