### ISSUE TITLE
[BUG] 500报错，找不到模型，不能生成Knowledge Base

### ISSUE THREAD

**Issue by meokey** [sugarforever/chat-ollama#97]
我是在相同的host上独立运行Ollama和Chroma的。Chroma显示`{"detail":"Not Found"}`表示运行正常，Ollama Open WebUI连接Ollama没有问题，可以显示已经有3个模型了。

我在chatollama配置了Ollama和Chroma的连接，也配置了Anthropic的API，但是不显示任何模型，Ollama和Claude的模型都不显示。可以保存Instruction。不能生成Knowledge Base显示fetch failed（应该是不能调用embedding吧）。

查看docker的logs，显示如下：
`Ollama:  { host: 'http://172.17.0.11:11434', username: null, password: null }
Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA==
[nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11576:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)` 
相同的connection string，Ollama Open WebUI没有问题可以连接。

ChatOllma，Ollama，Chroma都是最新版本。

**Comment by sugarforever** [comment]
是容器化运行的chatollama吗？容器内chatollama访问不到独立容器里的Ollama吧？应该需要建立docker容器间的网络

**Comment by meokey** [comment]
> 是容器化运行的chatollama吗？容器内chatollama访问不到独立容器里的Ollama吧？应该需要建立docker容器间的网络

是的，chatollama和ollama都是独立的容器。我用172的docker内ip地址不能访问，今天试了试吧ollama映射到host的port，用host的ip和port就可以了。但是同样的172的docker的ip地址，Ollama Open WebUI就可以访问，有点点奇怪不知道为什么。也可能是我docker的设置比较奇怪（是Synology的docker，不知道是不是魔改版）？

如果你觉得我这个错误没有普遍性，就关了吧。我已经找到原因修复可以用了。

**Comment by githubjason-18** [comment]
我也遇到相同錯誤訊息，但我不知道該怎麼處理
我是ollama 、 chat-ollama 都是docker

錯誤訊息： Chat with Ollama, host: http://host.docker.internal:11434
chatollama-1  | Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }
chatollama-1  | Ollama:  {
chatollama-1  |   host: 'http://host.docker.internal:11434',
chatollama-1  |   username: null,
chatollama-1  |   password: null
chatollama-1  | }
chatollama-1  | Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA==
chatollama-1  | Created knowledge base HVAC1: 6
chatollama-1  | Creating embeddings for Ollama served model: nomic-embed-text
chatollama-1  | [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
chatollama-1  |   at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)

**Comment by meokey** [comment]
> 我也遇到相同錯誤訊息，但我不知道該怎麼處理 我是ollama 、 chat-ollama 都是docker
> 
> 錯誤訊息： Chat with Ollama, host: http://host.docker.internal:11434 chatollama-1 | Ollama: { host: 'http://127.0.0.1:11434', username: null, password: null } chatollama-1 | Ollama: { chatollama-1 | host: 'http://host.docker.internal:11434', chatollama-1 | username: null, chatollama-1 | password: null chatollama-1 | } chatollama-1 | Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA== chatollama-1 | Created knowledge base HVAC1: 6 chatollama-1 | Creating embeddings for Ollama served model: nomic-embed-text chatollama-1 | [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed chatollama-1 | at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)

我的解决方法是把container的port映射到主机host，然后ChatOllama用host的ip和port来连接。这个方法虽然安全性差些但能够work，呵呵
我以后还是有必要整理一下docker的网络设置，尽量在docker内部连接。

**Comment by sugarforever** [comment]
> > 我也遇到相同錯誤訊息，但我不知道該怎麼處理 我是ollama 、 chat-ollama 都是docker
> > 錯誤訊息： Chat with Ollama, host: http://host.docker.internal:11434 chatollama-1 | Ollama: { host: 'http://127.0.0.1:11434', username: null, password: null } chatollama-1 | Ollama: { chatollama-1 | host: 'http://host.docker.internal:11434', chatollama-1 | username: null, chatollama-1 | password: null chatollama-1 | } chatollama-1 | Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA== chatollama-1 | Created knowledge base HVAC1: 6 chatollama-1 | Creating embeddings for Ollama served model: nomic-embed-text chatollama-1 | [nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed chatollama-1 | at Chroma.ensureCollection (./.output/server/node_modules/@langchain/community/dist/vectorstores/chroma.js:99:23)
> 
> 我的解决方法是把container的port映射到主机host，然后ChatOllama用host的ip和port来连接。这个方法虽然安全性差些但能够work，呵呵 我以后还是有必要整理一下docker的网络设置，尽量在docker内部连接。

@githubjason-18 问题解决了吗

**Comment by liangnet** [comment]
我也有類似的問題
我在 Setting 裡設置了 Azure OpenAI, 要等一下才能開始使在 Chat 裡挑選, 但在 knowledge base 裡的 Embedding 貼上 同一個 Azure OpenAI 的 APP Key  的 deploy model, 都一直 500 internal server error
<img width="364" alt="截圖 2024-04-14 下午2 45 01" src="https://github.com/sugarforever/chat-ollama/assets/13990562/b869d484-b415-460e-8068-c61f9ab711c5">

**Comment by samisme0818** [comment]
同样的报错：[nuxt] [request error] [unhandled] [500] Chroma getOrCreateCollection error: Error: TypeError: fetch failed
